//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoAbilityUnitTypeComponent
{
    
    public static void AddAbilityUnitTypeComponent(this GXGame.SkillEntity effEntity)
    {
        effEntity.AddComponent<GXGame.AbilityUnitTypeComponent>();
    }
    
    public static void AddAbilityUnitTypeComponent(this GXGame.SkillEntity effEntity,GXGame.UnitTypeEnum param)
    {
        var p  =  (GXGame.AbilityUnitTypeComponent)effEntity.AddComponent<GXGame.AbilityUnitTypeComponent>();
        p.AbilityUnitTargetTeam = param;
    }
          
    public static GXGame.AbilityUnitTypeComponent GetAbilityUnitTypeComponent(this GXGame.SkillEntity effEntity)
    {
        return (GXGame.AbilityUnitTypeComponent)effEntity.GetComponent(ComponentsID<GXGame.AbilityUnitTypeComponent>.TID);
    }
     
    public static EffEntity SetAbilityUnitTypeComponent(this GXGame.SkillEntity effEntity,GXGame.UnitTypeEnum param)
    {
        var p = (GXGame.AbilityUnitTypeComponent)effEntity.GetComponent(ComponentsID<GXGame.AbilityUnitTypeComponent>.TID);
        p.AbilityUnitTargetTeam = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AbilityUnitTypeComponent>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetAbilityUnitTypeComponent(this GXGame.SkillEntity effEntity,GXGame.UnitTypeEnum param)
    {
        var p = (GXGame.AbilityUnitTypeComponent)effEntity.GetComponent(ComponentsID<GXGame.AbilityUnitTypeComponent>.TID);
        if(p==null)
        {
           p = (GXGame.AbilityUnitTypeComponent)(effEntity.AddComponent<GXGame.AbilityUnitTypeComponent>());
        }
        p.AbilityUnitTargetTeam = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AbilityUnitTypeComponent>.TID, effEntity);
        
        return effEntity;
    } 
         
}