//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoAssetPath
{
    
    public static void AddAssetPath(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent<GXGame.AssetPath>();
    }
    
    public static void AddAssetPath(this ECSEntity ecsEntity,System.String param)
    {
        var p  =  (GXGame.AssetPath)ecsEntity.AddComponent<GXGame.AssetPath>();
        p.Value = param;
    }
          
    public static GXGame.AssetPath GetAssetPath(this ECSEntity ecsEntity)
    {
        return (GXGame.AssetPath)ecsEntity.GetComponent(ComponentsID<GXGame.AssetPath>.TID);
    }
     
    public static ECSEntity SetAssetPath(this ECSEntity ecsEntity,System.String param)
    {
        var p = (GXGame.AssetPath)ecsEntity.GetComponent(ComponentsID<GXGame.AssetPath>.TID);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(ComponentsID<GXGame.AssetPath>.TID, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetAssetPath(this ECSEntity ecsEntity,System.String param)
    {
        var p = (GXGame.AssetPath)ecsEntity.GetComponent(ComponentsID<GXGame.AssetPath>.TID);
        if(p==null)
        {
           p = (GXGame.AssetPath)(ecsEntity.AddComponent<GXGame.AssetPath>());
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(ComponentsID<GXGame.AssetPath>.TID, ecsEntity);
        
        return ecsEntity;
    } 
         
}