//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoAtkCountdownComp
{
    
    public static void AddAtkCountdownComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.AtkCountdownComp>();
    }
    
    public static void AddAtkCountdownComp(this EffEntity effEntity,System.Single param)
    {
        var p  =  (GXGame.AtkCountdownComp)effEntity.AddComponent<GXGame.AtkCountdownComp>();
        p.Value = param;
    }
          
    public static GXGame.AtkCountdownComp GetAtkCountdownComp(this EffEntity effEntity)
    {
        return (GXGame.AtkCountdownComp)effEntity.GetComponent(ComponentsID<GXGame.AtkCountdownComp>.TID);
    }
     
    public static EffEntity SetAtkCountdownComp(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.AtkCountdownComp)effEntity.GetComponent(ComponentsID<GXGame.AtkCountdownComp>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AtkCountdownComp>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetAtkCountdownComp(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.AtkCountdownComp)effEntity.GetComponent(ComponentsID<GXGame.AtkCountdownComp>.TID);
        if(p==null)
        {
           p = (GXGame.AtkCountdownComp)(effEntity.AddComponent<GXGame.AtkCountdownComp>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AtkCountdownComp>.TID, effEntity);
        
        return effEntity;
    } 
         
}