//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoAtkIntervalComponent
{
    
    public static void AddAtkIntervalComponent(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.AtkIntervalComponent>();
    }
    
    public static void AddAtkIntervalComponent(this EffEntity effEntity,System.Single param)
    {
        var p  =  (GXGame.AtkIntervalComponent)effEntity.AddComponent<GXGame.AtkIntervalComponent>();
        p.Time = param;
    }
          
    public static GXGame.AtkIntervalComponent GetAtkIntervalComponent(this EffEntity effEntity)
    {
        return (GXGame.AtkIntervalComponent)effEntity.GetComponent(ComponentsID<GXGame.AtkIntervalComponent>.TID);
    }
     
    public static EffEntity SetAtkIntervalComponent(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.AtkIntervalComponent)effEntity.GetComponent(ComponentsID<GXGame.AtkIntervalComponent>.TID);
        p.Time = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AtkIntervalComponent>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetAtkIntervalComponent(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.AtkIntervalComponent)effEntity.GetComponent(ComponentsID<GXGame.AtkIntervalComponent>.TID);
        if(p==null)
        {
           p = (GXGame.AtkIntervalComponent)(effEntity.AddComponent<GXGame.AtkIntervalComponent>());
        }
        p.Time = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AtkIntervalComponent>.TID, effEntity);
        
        return effEntity;
    } 
         
}