//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoAtkOverComp
{
    
    public static void AddAtkOverComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.AtkOverComp>();
    }
    
    public static void AddAtkOverComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  (GXGame.AtkOverComp)effEntity.AddComponent<GXGame.AtkOverComp>();
        p.Value = param;
    }
          
    public static GXGame.AtkOverComp GetAtkOverComp(this EffEntity effEntity)
    {
        return (GXGame.AtkOverComp)effEntity.GetComponent(ComponentsID<GXGame.AtkOverComp>.TID);
    }
     
    public static EffEntity SetAtkOverComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = (GXGame.AtkOverComp)effEntity.GetComponent(ComponentsID<GXGame.AtkOverComp>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AtkOverComp>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.IAtkOverComp) (view.Value)).AtkOverComp(p);
        return effEntity;
    }
    
    public static EffEntity AddOrSetAtkOverComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = (GXGame.AtkOverComp)effEntity.GetComponent(ComponentsID<GXGame.AtkOverComp>.TID);
        if(p==null)
        {
           p = (GXGame.AtkOverComp)(effEntity.AddComponent<GXGame.AtkOverComp>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AtkOverComp>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.IAtkOverComp) (view.Value)).AtkOverComp(p);
        return effEntity;
    } 
         
}