//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoAtkStartComp
{
    
    public static void AddAtkStartComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.AtkStartComp>();
    }
    
    public static void AddAtkStartComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  (GXGame.AtkStartComp)effEntity.AddComponent<GXGame.AtkStartComp>();
        p.Value = param;
    }
          
    public static GXGame.AtkStartComp GetAtkStartComp(this EffEntity effEntity)
    {
        return (GXGame.AtkStartComp)effEntity.GetComponent(ComponentsID<GXGame.AtkStartComp>.TID);
    }
     
    public static EffEntity SetAtkStartComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = (GXGame.AtkStartComp)effEntity.GetComponent(ComponentsID<GXGame.AtkStartComp>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AtkStartComp>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.IAtkComp) (view.Value)).AtkComp(p);
        return effEntity;
    }
    
    public static EffEntity AddOrSetAtkStartComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = (GXGame.AtkStartComp)effEntity.GetComponent(ComponentsID<GXGame.AtkStartComp>.TID);
        if(p==null)
        {
           p = (GXGame.AtkStartComp)(effEntity.AddComponent<GXGame.AtkStartComp>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.AtkStartComp>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.IAtkComp) (view.Value)).AtkComp(p);
        return effEntity;
    } 
         
}