//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoBehaviorTreeComponent
{
    
    public static void AddBehaviorTreeComponent(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.BehaviorTreeComponent>();
    }
    
    public static void AddBehaviorTreeComponent(this EffEntity effEntity,System.String param)
    {
        var p  =  (GXGame.BehaviorTreeComponent)effEntity.AddComponent<GXGame.BehaviorTreeComponent>();
        p.Value = param;
    }
          
    public static GXGame.BehaviorTreeComponent GetBehaviorTreeComponent(this EffEntity effEntity)
    {
        return (GXGame.BehaviorTreeComponent)effEntity.GetComponent(ComponentsID<GXGame.BehaviorTreeComponent>.TID);
    }
     
    public static EffEntity SetBehaviorTreeComponent(this EffEntity effEntity,System.String param)
    {
        var p = (GXGame.BehaviorTreeComponent)effEntity.GetComponent(ComponentsID<GXGame.BehaviorTreeComponent>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.BehaviorTreeComponent>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetBehaviorTreeComponent(this EffEntity effEntity,System.String param)
    {
        var p = (GXGame.BehaviorTreeComponent)effEntity.GetComponent(ComponentsID<GXGame.BehaviorTreeComponent>.TID);
        if(p==null)
        {
           p = (GXGame.BehaviorTreeComponent)(effEntity.AddComponent<GXGame.BehaviorTreeComponent>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.BehaviorTreeComponent>.TID, effEntity);
        
        return effEntity;
    } 
         
}