//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoCampComponent
{
    
    public static void AddCampComponent(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.CampComponent>();
    }
    
    public static void AddCampComponent(this EffEntity effEntity,GXGame.Camp param)
    {
        var p  =  (GXGame.CampComponent)effEntity.AddComponent<GXGame.CampComponent>();
        p.Value = param;
    }
          
    public static GXGame.CampComponent GetCampComponent(this EffEntity effEntity)
    {
        return (GXGame.CampComponent)effEntity.GetComponent(ComponentsID<GXGame.CampComponent>.TID);
    }
     
    public static EffEntity SetCampComponent(this EffEntity effEntity,GXGame.Camp param)
    {
        var p = (GXGame.CampComponent)effEntity.GetComponent(ComponentsID<GXGame.CampComponent>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.CampComponent>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetCampComponent(this EffEntity effEntity,GXGame.Camp param)
    {
        var p = (GXGame.CampComponent)effEntity.GetComponent(ComponentsID<GXGame.CampComponent>.TID);
        if(p==null)
        {
           p = (GXGame.CampComponent)(effEntity.AddComponent<GXGame.CampComponent>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.CampComponent>.TID, effEntity);
        
        return effEntity;
    } 
         
}