//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoCampComponent
{
    
    public static void AddCampComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent<GXGame.CampComponent>();
    }
    
    public static void AddCampComponent(this ECSEntity ecsEntity,GXGame.Camp param)
    {
        var p  =  (GXGame.CampComponent)ecsEntity.AddComponent<GXGame.CampComponent>();
        p.Value = param;
    }
          
    public static GXGame.CampComponent GetCampComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.CampComponent)ecsEntity.GetComponent(ComponentsID<GXGame.CampComponent>.TID);
    }
     
    public static ECSEntity SetCampComponent(this ECSEntity ecsEntity,GXGame.Camp param)
    {
        var p = (GXGame.CampComponent)ecsEntity.GetComponent(ComponentsID<GXGame.CampComponent>.TID);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(ComponentsID<GXGame.CampComponent>.TID, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetCampComponent(this ECSEntity ecsEntity,GXGame.Camp param)
    {
        var p = (GXGame.CampComponent)ecsEntity.GetComponent(ComponentsID<GXGame.CampComponent>.TID);
        if(p==null)
        {
           p = (GXGame.CampComponent)(ecsEntity.AddComponent<GXGame.CampComponent>());
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(ComponentsID<GXGame.CampComponent>.TID, ecsEntity);
        
        return ecsEntity;
    } 
         
}