//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoCapabiltyComponent
{
    
    public static void AddCapabiltyComponent(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.CapabiltyComponent>();
    }
          
    public static GameFrame.Runtime.CapabiltyComponent GetCapabiltyComponent(this EffEntity effEntity)
    {
        return (GameFrame.Runtime.CapabiltyComponent)effEntity.GetComponent(ComponentsID<GameFrame.Runtime.CapabiltyComponent>.TID);
    }
         
}