//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoCapabiltyComponent
{
    
    public static void AddCapabiltyComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent<GameFrame.Runtime.SH.CapabiltyComponent>();
    }
          
    public static GameFrame.Runtime.SH.CapabiltyComponent GetCapabiltyComponent(this ECSEntity ecsEntity)
    {
        return (GameFrame.Runtime.SH.CapabiltyComponent)ecsEntity.GetComponent(ComponentsID<GameFrame.Runtime.SH.CapabiltyComponent>.TID);
    }
         
}