//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoCollisionGroundType
{
    
    public static void AddCollisionGroundType(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.CollisionGroundType>();
    }
    
    public static void AddCollisionGroundType(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  (GXGame.CollisionGroundType)effEntity.AddComponent<GXGame.CollisionGroundType>();
        p.Type = param;
    }
          
    public static GXGame.CollisionGroundType GetCollisionGroundType(this EffEntity effEntity)
    {
        return (GXGame.CollisionGroundType)effEntity.GetComponent(ComponentsID<GXGame.CollisionGroundType>.TID);
    }
     
    public static EffEntity SetCollisionGroundType(this EffEntity effEntity,System.Int32 param)
    {
        var p = (GXGame.CollisionGroundType)effEntity.GetComponent(ComponentsID<GXGame.CollisionGroundType>.TID);
        p.Type = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.CollisionGroundType>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetCollisionGroundType(this EffEntity effEntity,System.Int32 param)
    {
        var p = (GXGame.CollisionGroundType)effEntity.GetComponent(ComponentsID<GXGame.CollisionGroundType>.TID);
        if(p==null)
        {
           p = (GXGame.CollisionGroundType)(effEntity.AddComponent<GXGame.CollisionGroundType>());
        }
        p.Type = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.CollisionGroundType>.TID, effEntity);
        
        return effEntity;
    } 
         
}