//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoDestroyCountdown
{
    
    public static void AddDestroyCountdown(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.DestroyCountdown>();
    }
    
    public static void AddDestroyCountdown(this EffEntity effEntity,System.Single param)
    {
        var p  =  (GXGame.DestroyCountdown)effEntity.AddComponent<GXGame.DestroyCountdown>();
        p.Value = param;
    }
          
    public static GXGame.DestroyCountdown GetDestroyCountdown(this EffEntity effEntity)
    {
        return (GXGame.DestroyCountdown)effEntity.GetComponent(ComponentsID<GXGame.DestroyCountdown>.TID);
    }
     
    public static EffEntity SetDestroyCountdown(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.DestroyCountdown)effEntity.GetComponent(ComponentsID<GXGame.DestroyCountdown>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.DestroyCountdown>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetDestroyCountdown(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.DestroyCountdown)effEntity.GetComponent(ComponentsID<GXGame.DestroyCountdown>.TID);
        if(p==null)
        {
           p = (GXGame.DestroyCountdown)(effEntity.AddComponent<GXGame.DestroyCountdown>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.DestroyCountdown>.TID, effEntity);
        
        return effEntity;
    } 
         
}