//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoDestroyComp
{
    
    public static void AddDestroyComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.DestroyComp>();
    }
          
    public static GameFrame.Runtime.DestroyComp GetDestroyComp(this EffEntity effEntity)
    {
        return (GameFrame.Runtime.DestroyComp)effEntity.GetComponent(ComponentsID<GameFrame.Runtime.DestroyComp>.TID);
    }
         
}