//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoDestroy
{
    
    public static void AddDestroy(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.Destroy>();
    }
          
    public static GameFrame.Runtime.Destroy GetDestroy(this EffEntity effEntity)
    {
        return (GameFrame.Runtime.Destroy)effEntity.GetComponent(ComponentsID<GameFrame.Runtime.Destroy>.TID);
    }
         
}