//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoFaceDirection
{
    
    public static void AddFaceDirection(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.FaceDirection>();
    }
    
    public static void AddFaceDirection(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  (GXGame.FaceDirection)effEntity.AddComponent<GXGame.FaceDirection>();
        p.Value = param;
    }
          
    public static GXGame.FaceDirection GetFaceDirection(this EffEntity effEntity)
    {
        return (GXGame.FaceDirection)effEntity.GetComponent(ComponentsID<GXGame.FaceDirection>.TID);
    }
     
    public static EffEntity SetFaceDirection(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.FaceDirection)effEntity.GetComponent(ComponentsID<GXGame.FaceDirection>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.FaceDirection>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetFaceDirection(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.FaceDirection)effEntity.GetComponent(ComponentsID<GXGame.FaceDirection>.TID);
        if(p==null)
        {
           p = (GXGame.FaceDirection)(effEntity.AddComponent<GXGame.FaceDirection>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.FaceDirection>.TID, effEntity);
        
        return effEntity;
    } 
         
}