//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoGXInput
{
    
    public static void AddGXInput(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.GXInput>();
    }
          
    public static GXGame.GXInput GetGXInput(this EffEntity effEntity)
    {
        return (GXGame.GXInput)effEntity.GetComponent(ComponentsID<GXGame.GXInput>.TID);
    }
         
}