//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoLateSkillComponent
{
    
    public static void AddLateSkillComponent(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.LateSkillComponent>();
    }
    
    public static void AddLateSkillComponent(this EffEntity effEntity,System.Single param)
    {
        var p  =  (GXGame.LateSkillComponent)effEntity.AddComponent<GXGame.LateSkillComponent>();
        p.Time = param;
    }
          
    public static GXGame.LateSkillComponent GetLateSkillComponent(this EffEntity effEntity)
    {
        return (GXGame.LateSkillComponent)effEntity.GetComponent(ComponentsID<GXGame.LateSkillComponent>.TID);
    }
     
    public static EffEntity SetLateSkillComponent(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.LateSkillComponent)effEntity.GetComponent(ComponentsID<GXGame.LateSkillComponent>.TID);
        p.Time = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.LateSkillComponent>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetLateSkillComponent(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.LateSkillComponent)effEntity.GetComponent(ComponentsID<GXGame.LateSkillComponent>.TID);
        if(p==null)
        {
           p = (GXGame.LateSkillComponent)(effEntity.AddComponent<GXGame.LateSkillComponent>());
        }
        p.Time = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.LateSkillComponent>.TID, effEntity);
        
        return effEntity;
    } 
         
}