//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoLocalPos
{
    
    public static void AddLocalPos(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.LocalPos>();
    }
    
    public static void AddLocalPos(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  (GXGame.LocalPos)effEntity.AddComponent<GXGame.LocalPos>();
        p.Value = param;
    }
          
    public static GXGame.LocalPos GetLocalPos(this EffEntity effEntity)
    {
        return (GXGame.LocalPos)effEntity.GetComponent(ComponentsID<GXGame.LocalPos>.TID);
    }
     
    public static EffEntity SetLocalPos(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.LocalPos)effEntity.GetComponent(ComponentsID<GXGame.LocalPos>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.LocalPos>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.ILocalPosition) (view.Value)).LocalPosition(p);
        return effEntity;
    }
    
    public static EffEntity AddOrSetLocalPos(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.LocalPos)effEntity.GetComponent(ComponentsID<GXGame.LocalPos>.TID);
        if(p==null)
        {
           p = (GXGame.LocalPos)(effEntity.AddComponent<GXGame.LocalPos>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.LocalPos>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.ILocalPosition) (view.Value)).LocalPosition(p);
        return effEntity;
    } 
         
}