//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoLocalScale
{
    
    public static void AddLocalScale(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.LocalScale>();
    }
    
    public static void AddLocalScale(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  (GXGame.LocalScale)effEntity.AddComponent<GXGame.LocalScale>();
        p.Value = param;
    }
          
    public static GXGame.LocalScale GetLocalScale(this EffEntity effEntity)
    {
        return (GXGame.LocalScale)effEntity.GetComponent(ComponentsID<GXGame.LocalScale>.TID);
    }
     
    public static EffEntity SetLocalScale(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.LocalScale)effEntity.GetComponent(ComponentsID<GXGame.LocalScale>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.LocalScale>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.ILocalScale) (view.Value)).LocalScale(p);
        return effEntity;
    }
    
    public static EffEntity AddOrSetLocalScale(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.LocalScale)effEntity.GetComponent(ComponentsID<GXGame.LocalScale>.TID);
        if(p==null)
        {
           p = (GXGame.LocalScale)(effEntity.AddComponent<GXGame.LocalScale>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.LocalScale>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.ILocalScale) (view.Value)).LocalScale(p);
        return effEntity;
    } 
         
}