//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoLocalRotate
{
    
    public static void AddLocalRotate(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.LocalRotate>();
    }
    
    public static void AddLocalRotate(this EffEntity effEntity,UnityEngine.Quaternion param)
    {
        var p  =  (GXGame.LocalRotate)effEntity.AddComponent<GXGame.LocalRotate>();
        p.Value = param;
    }
          
    public static GXGame.LocalRotate GetLocalRotate(this EffEntity effEntity)
    {
        return (GXGame.LocalRotate)effEntity.GetComponent(ComponentsID<GXGame.LocalRotate>.TID);
    }
     
    public static EffEntity SetLocalRotate(this EffEntity effEntity,UnityEngine.Quaternion param)
    {
        var p = (GXGame.LocalRotate)effEntity.GetComponent(ComponentsID<GXGame.LocalRotate>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.LocalRotate>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.ILocalRotate) (view.Value)).LocalRotate(p);
        return effEntity;
    }
    
    public static EffEntity AddOrSetLocalRotate(this EffEntity effEntity,UnityEngine.Quaternion param)
    {
        var p = (GXGame.LocalRotate)effEntity.GetComponent(ComponentsID<GXGame.LocalRotate>.TID);
        if(p==null)
        {
           p = (GXGame.LocalRotate)(effEntity.AddComponent<GXGame.LocalRotate>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.LocalRotate>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.ILocalRotate) (view.Value)).LocalRotate(p);
        return effEntity;
    } 
         
}