//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoMeshRendererColor
{
    
    public static void AddMeshRendererColor(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.MeshRendererColor>();
    }
    
    public static void AddMeshRendererColor(this EffEntity effEntity,UnityEngine.Color param)
    {
        var p  =  (GXGame.MeshRendererColor)effEntity.AddComponent<GXGame.MeshRendererColor>();
        p.Value = param;
    }
          
    public static GXGame.MeshRendererColor GetMeshRendererColor(this EffEntity effEntity)
    {
        return (GXGame.MeshRendererColor)effEntity.GetComponent(ComponentsID<GXGame.MeshRendererColor>.TID);
    }
     
    public static EffEntity SetMeshRendererColor(this EffEntity effEntity,UnityEngine.Color param)
    {
        var p = (GXGame.MeshRendererColor)effEntity.GetComponent(ComponentsID<GXGame.MeshRendererColor>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.MeshRendererColor>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetMeshRendererColor(this EffEntity effEntity,UnityEngine.Color param)
    {
        var p = (GXGame.MeshRendererColor)effEntity.GetComponent(ComponentsID<GXGame.MeshRendererColor>.TID);
        if(p==null)
        {
           p = (GXGame.MeshRendererColor)(effEntity.AddComponent<GXGame.MeshRendererColor>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.MeshRendererColor>.TID, effEntity);
        
        return effEntity;
    } 
         
}