//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoMonster
{
    
    public static void AddMonster(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent<GXGame.Monster>();
    }
          
    public static GXGame.Monster GetMonster(this ECSEntity ecsEntity)
    {
        return (GXGame.Monster)ecsEntity.GetComponent(ComponentsID<GXGame.Monster>.TID);
    }
         
}