//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoMonster
{
    
    public static void AddMonster(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.Monster>();
    }
          
    public static GXGame.Monster GetMonster(this EffEntity effEntity)
    {
        return (GXGame.Monster)effEntity.GetComponent(ComponentsID<GXGame.Monster>.TID);
    }
         
}