//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoMoveSpeed
{
    
    public static void AddMoveSpeed(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.MoveSpeed>();
    }
    
    public static void AddMoveSpeed(this EffEntity effEntity,System.Single param)
    {
        var p  =  (GXGame.MoveSpeed)effEntity.AddComponent<GXGame.MoveSpeed>();
        p.Value = param;
    }
          
    public static GXGame.MoveSpeed GetMoveSpeed(this EffEntity effEntity)
    {
        return (GXGame.MoveSpeed)effEntity.GetComponent(ComponentsID<GXGame.MoveSpeed>.TID);
    }
     
    public static EffEntity SetMoveSpeed(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.MoveSpeed)effEntity.GetComponent(ComponentsID<GXGame.MoveSpeed>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.MoveSpeed>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetMoveSpeed(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.MoveSpeed)effEntity.GetComponent(ComponentsID<GXGame.MoveSpeed>.TID);
        if(p==null)
        {
           p = (GXGame.MoveSpeed)(effEntity.AddComponent<GXGame.MoveSpeed>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.MoveSpeed>.TID, effEntity);
        
        return effEntity;
    } 
         
}