//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoMoveDirection
{
    
    public static void AddMoveDirection(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.MoveDirection>();
    }
    
    public static void AddMoveDirection(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  (GXGame.MoveDirection)effEntity.AddComponent<GXGame.MoveDirection>();
        p.Value = param;
    }
          
    public static GXGame.MoveDirection GetMoveDirection(this EffEntity effEntity)
    {
        return (GXGame.MoveDirection)effEntity.GetComponent(ComponentsID<GXGame.MoveDirection>.TID);
    }
     
    public static EffEntity SetMoveDirection(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.MoveDirection)effEntity.GetComponent(ComponentsID<GXGame.MoveDirection>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.MoveDirection>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetMoveDirection(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.MoveDirection)effEntity.GetComponent(ComponentsID<GXGame.MoveDirection>.TID);
        if(p==null)
        {
           p = (GXGame.MoveDirection)(effEntity.AddComponent<GXGame.MoveDirection>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.MoveDirection>.TID, effEntity);
        
        return effEntity;
    } 
         
}