//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoPlayer
{
    
    public static void AddPlayer(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.Player>();
    }
          
    public static GXGame.Player GetPlayer(this EffEntity effEntity)
    {
        return (GXGame.Player)effEntity.GetComponent(ComponentsID<GXGame.Player>.TID);
    }
         
}