//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoPlayer
{
    
    public static void AddPlayer(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent<GXGame.Player>();
    }
          
    public static GXGame.Player GetPlayer(this ECSEntity ecsEntity)
    {
        return (GXGame.Player)ecsEntity.GetComponent(ComponentsID<GXGame.Player>.TID);
    }
         
}