//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoPreSkillComponent
{
    
    public static void AddPreSkillComponent(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.PreSkillComponent>();
    }
    
    public static void AddPreSkillComponent(this EffEntity effEntity,System.Single param)
    {
        var p  =  (GXGame.PreSkillComponent)effEntity.AddComponent<GXGame.PreSkillComponent>();
        p.Time = param;
    }
          
    public static GXGame.PreSkillComponent GetPreSkillComponent(this EffEntity effEntity)
    {
        return (GXGame.PreSkillComponent)effEntity.GetComponent(ComponentsID<GXGame.PreSkillComponent>.TID);
    }
     
    public static EffEntity SetPreSkillComponent(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.PreSkillComponent)effEntity.GetComponent(ComponentsID<GXGame.PreSkillComponent>.TID);
        p.Time = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.PreSkillComponent>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetPreSkillComponent(this EffEntity effEntity,System.Single param)
    {
        var p = (GXGame.PreSkillComponent)effEntity.GetComponent(ComponentsID<GXGame.PreSkillComponent>.TID);
        if(p==null)
        {
           p = (GXGame.PreSkillComponent)(effEntity.AddComponent<GXGame.PreSkillComponent>());
        }
        p.Time = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.PreSkillComponent>.TID, effEntity);
        
        return effEntity;
    } 
         
}