//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoRaycastHit
{
    
    public static void AddRaycastHit(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.RaycastHit>();
    }
    
    public static void AddRaycastHit(this EffEntity effEntity,System.Collections.Generic.List<UnityEngine.RaycastHit2D> param)
    {
        var p  =  (GXGame.RaycastHit)effEntity.AddComponent<GXGame.RaycastHit>();
        p.Value = param;
    }
          
    public static GXGame.RaycastHit GetRaycastHit(this EffEntity effEntity)
    {
        return (GXGame.RaycastHit)effEntity.GetComponent(ComponentsID<GXGame.RaycastHit>.TID);
    }
     
    public static EffEntity SetRaycastHit(this EffEntity effEntity,System.Collections.Generic.List<UnityEngine.RaycastHit2D> param)
    {
        var p = (GXGame.RaycastHit)effEntity.GetComponent(ComponentsID<GXGame.RaycastHit>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.RaycastHit>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetRaycastHit(this EffEntity effEntity,System.Collections.Generic.List<UnityEngine.RaycastHit2D> param)
    {
        var p = (GXGame.RaycastHit)effEntity.GetComponent(ComponentsID<GXGame.RaycastHit>.TID);
        if(p==null)
        {
           p = (GXGame.RaycastHit)(effEntity.AddComponent<GXGame.RaycastHit>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.RaycastHit>.TID, effEntity);
        
        return effEntity;
    } 
         
}