//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoSkillComponent
{
    
    public static void AddSkillComponent(this GXGame.SkillEntity effEntity)
    {
        effEntity.AddComponent<GXGame.SkillComponent>();
    }
    
    public static void AddSkillComponent(this GXGame.SkillEntity effEntity,System.Int32 param)
    {
        var p  =  (GXGame.SkillComponent)effEntity.AddComponent<GXGame.SkillComponent>();
        p.ID = param;
    }
          
    public static GXGame.SkillComponent GetSkillComponent(this GXGame.SkillEntity effEntity)
    {
        return (GXGame.SkillComponent)effEntity.GetComponent(ComponentsID<GXGame.SkillComponent>.TID);
    }
     
    public static EffEntity SetSkillComponent(this GXGame.SkillEntity effEntity,System.Int32 param)
    {
        var p = (GXGame.SkillComponent)effEntity.GetComponent(ComponentsID<GXGame.SkillComponent>.TID);
        p.ID = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.SkillComponent>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetSkillComponent(this GXGame.SkillEntity effEntity,System.Int32 param)
    {
        var p = (GXGame.SkillComponent)effEntity.GetComponent(ComponentsID<GXGame.SkillComponent>.TID);
        if(p==null)
        {
           p = (GXGame.SkillComponent)(effEntity.AddComponent<GXGame.SkillComponent>());
        }
        p.ID = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.SkillComponent>.TID, effEntity);
        
        return effEntity;
    } 
         
}