//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoUnitTypeComponent
{
    
    public static void AddUnitTypeComponent(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent<GXGame.UnitTypeComponent>();
    }
    
    public static void AddUnitTypeComponent(this ECSEntity ecsEntity,GXGame.UnitTypeEnum param)
    {
        var p  =  (GXGame.UnitTypeComponent)ecsEntity.AddComponent<GXGame.UnitTypeComponent>();
        p.Value = param;
    }
          
    public static GXGame.UnitTypeComponent GetUnitTypeComponent(this ECSEntity ecsEntity)
    {
        return (GXGame.UnitTypeComponent)ecsEntity.GetComponent(ComponentsID<GXGame.UnitTypeComponent>.TID);
    }
     
    public static ECSEntity SetUnitTypeComponent(this ECSEntity ecsEntity,GXGame.UnitTypeEnum param)
    {
        var p = (GXGame.UnitTypeComponent)ecsEntity.GetComponent(ComponentsID<GXGame.UnitTypeComponent>.TID);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(ComponentsID<GXGame.UnitTypeComponent>.TID, ecsEntity);
        
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetUnitTypeComponent(this ECSEntity ecsEntity,GXGame.UnitTypeEnum param)
    {
        var p = (GXGame.UnitTypeComponent)ecsEntity.GetComponent(ComponentsID<GXGame.UnitTypeComponent>.TID);
        if(p==null)
        {
           p = (GXGame.UnitTypeComponent)(ecsEntity.AddComponent<GXGame.UnitTypeComponent>());
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(ComponentsID<GXGame.UnitTypeComponent>.TID, ecsEntity);
        
        return ecsEntity;
    } 
         
}