//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoUseShareMaterial
{
    
    public static void AddUseShareMaterial(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.UseShareMaterial>();
    }
          
    public static GXGame.UseShareMaterial GetUseShareMaterial(this EffEntity effEntity)
    {
        return (GXGame.UseShareMaterial)effEntity.GetComponent(ComponentsID<GXGame.UseShareMaterial>.TID);
    }
         
}