//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoViewType
{
    
    public static void AddViewType(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.ViewType>();
    }
    
    public static void AddViewType(this EffEntity effEntity,System.Type param)
    {
        var p  =  (GXGame.ViewType)effEntity.AddComponent<GXGame.ViewType>();
        p.Value = param;
    }
          
    public static GXGame.ViewType GetViewType(this EffEntity effEntity)
    {
        return (GXGame.ViewType)effEntity.GetComponent(ComponentsID<GXGame.ViewType>.TID);
    }
     
    public static EffEntity SetViewType(this EffEntity effEntity,System.Type param)
    {
        var p = (GXGame.ViewType)effEntity.GetComponent(ComponentsID<GXGame.ViewType>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.ViewType>.TID, effEntity);
        
        return effEntity;
    }
    
    public static EffEntity AddOrSetViewType(this EffEntity effEntity,System.Type param)
    {
        var p = (GXGame.ViewType)effEntity.GetComponent(ComponentsID<GXGame.ViewType>.TID);
        if(p==null)
        {
           p = (GXGame.ViewType)(effEntity.AddComponent<GXGame.ViewType>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.ViewType>.TID, effEntity);
        
        return effEntity;
    } 
         
}