//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static partial class AutoWorldPos
{
    
    public static void AddWorldPos(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent<GXGame.WorldPos>();
    }
    
    public static void AddWorldPos(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p  =  (GXGame.WorldPos)ecsEntity.AddComponent<GXGame.WorldPos>();
        p.Value = param;
    }
          
    public static GXGame.WorldPos GetWorldPos(this ECSEntity ecsEntity)
    {
        var id = ComponentsID<GXGame.WorldPos>.TID;
        return (GXGame.WorldPos)ecsEntity.GetComponent(ComponentsID<GXGame.WorldPos>.TID);
    }
     
    public static ECSEntity SetWorldPos(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.WorldPos)ecsEntity.GetComponent(ComponentsID<GXGame.WorldPos>.TID);
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(ComponentsID<GXGame.WorldPos>.TID, ecsEntity);
        View view = ecsEntity.GetView();
        if (view == null) return null;
        ((GXGame.IWolrdPosition) (view.Value)).WolrdPosition(p);
        return ecsEntity;
    }
    
    public static ECSEntity AddOrSetWorldPos(this ECSEntity ecsEntity,UnityEngine.Vector3 param)
    {
        var p = (GXGame.WorldPos)ecsEntity.GetComponent(ComponentsID<GXGame.WorldPos>.TID);
        if(p==null)
        {
           p = (GXGame.WorldPos)(ecsEntity.AddComponent<GXGame.WorldPos>());
        }
        p.Value = param;
        ((World)ecsEntity.Parent).Reactive(ComponentsID<GXGame.WorldPos>.TID, ecsEntity);
        View view = ecsEntity.GetView();
        if (view == null) return null;
        ((GXGame.IWolrdPosition) (view.Value)).WolrdPosition(p);
        return ecsEntity;
    } 
         
}