//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public static partial class AutoWorldRotate
{
    
    public static void AddWorldRotate(this EffEntity effEntity)
    {
        effEntity.AddComponent<GXGame.WorldRotate>();
    }
    
    public static void AddWorldRotate(this EffEntity effEntity,UnityEngine.Quaternion param)
    {
        var p  =  (GXGame.WorldRotate)effEntity.AddComponent<GXGame.WorldRotate>();
        p.Value = param;
    }
          
    public static GXGame.WorldRotate GetWorldRotate(this EffEntity effEntity)
    {
        return (GXGame.WorldRotate)effEntity.GetComponent(ComponentsID<GXGame.WorldRotate>.TID);
    }
     
    public static EffEntity SetWorldRotate(this EffEntity effEntity,UnityEngine.Quaternion param)
    {
        var p = (GXGame.WorldRotate)effEntity.GetComponent(ComponentsID<GXGame.WorldRotate>.TID);
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.WorldRotate>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.IWorldRotate) (view.Value)).WorldRotate(p);
        return effEntity;
    }
    
    public static EffEntity AddOrSetWorldRotate(this EffEntity effEntity,UnityEngine.Quaternion param)
    {
        var p = (GXGame.WorldRotate)effEntity.GetComponent(ComponentsID<GXGame.WorldRotate>.TID);
        if(p==null)
        {
           p = (GXGame.WorldRotate)(effEntity.AddComponent<GXGame.WorldRotate>());
        }
        p.Value = param;
        ((World)effEntity.Parent).Reactive(ComponentsID<GXGame.WorldRotate>.TID, effEntity);
        View view = effEntity.GetView();
        if (view == null) return null;
        ((GXGame.IWorldRotate) (view.Value)).WorldRotate(p);
        return effEntity;
    } 
         
}