
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public partial class AnimationTable
{
    private readonly System.Collections.Generic.Dictionary<int, AnimationItem> _dataMap;
    private readonly System.Collections.Generic.List<AnimationItem> _dataList;
    
    public AnimationTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, AnimationItem>(n);
        _dataList = new System.Collections.Generic.List<AnimationItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            AnimationItem _v;
            _v = global::GamePlay.Runtime.AnimationItem.DeserializeAnimationItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AnimationItem> DataMap => _dataMap;
    public System.Collections.Generic.List<AnimationItem> DataList => _dataList;

    public AnimationItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AnimationItem Get(int key) => _dataMap[key];
    public AnimationItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

