
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class AnimationItem : Luban.BeanBase
{
    public AnimationItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        AnimationHashIndex = _buf.ReadInt();
        BeforeTime = _buf.ReadFloat();
        ExecutionTime = _buf.ReadFloat();
        AfterTime = _buf.ReadFloat();
    }

    public static AnimationItem DeserializeAnimationItem(ByteBuf _buf)
    {
        return new AnimationItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 动画列表编号
    /// </summary>
    public readonly int AnimationHashIndex;
    /// <summary>
    /// 前摇时间，后面不写就是总时间
    /// </summary>
    public readonly float BeforeTime;
    /// <summary>
    /// 执行时间
    /// </summary>
    public readonly float ExecutionTime;
    /// <summary>
    /// 后摇时间
    /// </summary>
    public readonly float AfterTime;
   
    public const int __ID__ = -1465132905;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "AnimationHashIndex:" + AnimationHashIndex + ","
        + "BeforeTime:" + BeforeTime + ","
        + "ExecutionTime:" + ExecutionTime + ","
        + "AfterTime:" + AfterTime + ","
        + "}";
    }
}
}

