
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class AttributeItem : Luban.BeanBase
{
    public AttributeItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Atk = _buf.ReadInt();
        HP = _buf.ReadInt();
    }

    public static AttributeItem DeserializeAttributeItem(ByteBuf _buf)
    {
        return new AttributeItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    public readonly int Atk;
    public readonly int HP;
   
    public const int __ID__ = -650437713;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Atk:" + Atk + ","
        + "HP:" + HP + ","
        + "}";
    }
}
}

