
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public partial class AwardTable
{
    private readonly System.Collections.Generic.Dictionary<int, AwardItem> _dataMap;
    private readonly System.Collections.Generic.List<AwardItem> _dataList;
    
    public AwardTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, AwardItem>(n);
        _dataList = new System.Collections.Generic.List<AwardItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            AwardItem _v;
            _v = global::GamePlay.Runtime.AwardItem.DeserializeAwardItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, AwardItem> DataMap => _dataMap;
    public System.Collections.Generic.List<AwardItem> DataList => _dataList;

    public AwardItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public AwardItem Get(int key) => _dataMap[key];
    public AwardItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

