
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public partial class BattleBehaviorTable
{
    private readonly System.Collections.Generic.Dictionary<int, BattleBehaviorItem> _dataMap;
    private readonly System.Collections.Generic.List<BattleBehaviorItem> _dataList;
    
    public BattleBehaviorTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleBehaviorItem>(n);
        _dataList = new System.Collections.Generic.List<BattleBehaviorItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            BattleBehaviorItem _v;
            _v = global::GamePlay.Runtime.BattleBehaviorItem.DeserializeBattleBehaviorItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleBehaviorItem> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleBehaviorItem> DataList => _dataList;

    public BattleBehaviorItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleBehaviorItem Get(int key) => _dataMap[key];
    public BattleBehaviorItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

