
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class BattleBehaviorItem : Luban.BeanBase
{
    public BattleBehaviorItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        AtkDistance = _buf.ReadFloat();
        TrackDistance = _buf.ReadFloat();
    }

    public static BattleBehaviorItem DeserializeBattleBehaviorItem(ByteBuf _buf)
    {
        return new BattleBehaviorItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 最大攻击距离
    /// </summary>
    public readonly float AtkDistance;
    /// <summary>
    /// 最大追击距离
    /// </summary>
    public readonly float TrackDistance;
   
    public const int __ID__ = 211301757;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "AtkDistance:" + AtkDistance + ","
        + "TrackDistance:" + TrackDistance + ","
        + "}";
    }
}
}

