
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public partial class BehaviorTable
{
    private readonly System.Collections.Generic.Dictionary<int, BehaviorTableItem> _dataMap;
    private readonly System.Collections.Generic.List<BehaviorTableItem> _dataList;
    
    public BehaviorTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, BehaviorTableItem>(n);
        _dataList = new System.Collections.Generic.List<BehaviorTableItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            BehaviorTableItem _v;
            _v = global::GamePlay.Runtime.BehaviorTableItem.DeserializeBehaviorTableItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BehaviorTableItem> DataMap => _dataMap;
    public System.Collections.Generic.List<BehaviorTableItem> DataList => _dataList;

    public BehaviorTableItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BehaviorTableItem Get(int key) => _dataMap[key];
    public BehaviorTableItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

