
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class BehaviorTableItem : Luban.BeanBase
{
    public BehaviorTableItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        BehaviorName = _buf.ReadString();
        BattleBehavior = _buf.ReadInt();
        BattleBehavior_Ref = null;
        AtkAnimation = _buf.ReadInt();
        AtkAnimation_Ref = null;
    }

    public static BehaviorTableItem DeserializeBehaviorTableItem(ByteBuf _buf)
    {
        return new BehaviorTableItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly string BehaviorName;
    public readonly int BattleBehavior;
    public BattleBehaviorItem BattleBehavior_Ref;
    public readonly int AtkAnimation;
    public AnimationItem AtkAnimation_Ref;
   
    public const int __ID__ = 1368047023;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BattleBehavior_Ref = tables.BattleBehaviorTable.GetOrDefault(BattleBehavior);
        AtkAnimation_Ref = tables.AnimationTable.GetOrDefault(AtkAnimation);
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "BehaviorName:" + BehaviorName + ","
        + "BattleBehavior:" + BattleBehavior + ","
        + "AtkAnimation:" + AtkAnimation + ","
        + "}";
    }
}
}

