
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class BeOperated : Luban.BeanBase
{
    public BeOperated(ByteBuf _buf) 
    {
        {int __n0 = _buf.ReadSize(); OperatedTypes = new OperatedType[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { OperatedType __e0;__e0 = (OperatedType)_buf.ReadInt(); OperatedTypes[__index0] = __e0;}}
        if(_buf.ReadBool()){ BeOpAnimation = _buf.ReadInt(); } else { BeOpAnimation = null; }
        BeOpAnimation_Ref = null;
        OpType = (UnitOpType)_buf.ReadInt();
        ResultType = (ResultUnitOpType)_buf.ReadInt();
        if(_buf.ReadBool()){ ResultAward = global::GamePlay.Runtime.OpAward.DeserializeOpAward(_buf); } else { ResultAward = null; }
        ResultOpenUI = _buf.ReadString();
        if(_buf.ReadBool()){ TransmitData = global::GamePlay.Runtime.Transmit.DeserializeTransmit(_buf); } else { TransmitData = null; }
    }

    public static BeOperated DeserializeBeOperated(ByteBuf _buf)
    {
        return new BeOperated(_buf);
    }

    public readonly OperatedType[] OperatedTypes;
    public readonly int? BeOpAnimation;
    public AnimationItem BeOpAnimation_Ref;
    public readonly UnitOpType OpType;
    public readonly ResultUnitOpType ResultType;
    public readonly OpAward ResultAward;
    public readonly string ResultOpenUI;
    public readonly Transmit TransmitData;
   
    public const int __ID__ = 1609793763;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        BeOpAnimation_Ref = BeOpAnimation!= null ? tables.AnimationTable.GetOrDefault(BeOpAnimation.Value) : null;
        ResultAward?.ResolveRef(tables);
        TransmitData?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "OperatedTypes:" + Luban.StringUtil.CollectionToString(OperatedTypes) + ","
        + "BeOpAnimation:" + BeOpAnimation + ","
        + "OpType:" + OpType + ","
        + "ResultType:" + ResultType + ","
        + "ResultAward:" + ResultAward + ","
        + "ResultOpenUI:" + ResultOpenUI + ","
        + "TransmitData:" + TransmitData + ","
        + "}";
    }
}
}

