
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public partial class GrowthTable
{
    private readonly System.Collections.Generic.Dictionary<int, GrowthItem> _dataMap;
    private readonly System.Collections.Generic.List<GrowthItem> _dataList;
    
    public GrowthTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, GrowthItem>(n);
        _dataList = new System.Collections.Generic.List<GrowthItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            GrowthItem _v;
            _v = global::GamePlay.Runtime.GrowthItem.DeserializeGrowthItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GrowthItem> DataMap => _dataMap;
    public System.Collections.Generic.List<GrowthItem> DataList => _dataList;

    public GrowthItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GrowthItem Get(int key) => _dataMap[key];
    public GrowthItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

