
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class GrowthItem : Luban.BeanBase
{
    public GrowthItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        if(_buf.ReadBool()){ NextState = _buf.ReadInt(); } else { NextState = null; }
        PersistentDay = _buf.ReadInt();
        if(_buf.ReadBool()){ AfterPickingState = _buf.ReadInt(); } else { AfterPickingState = null; }
    }

    public static GrowthItem DeserializeGrowthItem(ByteBuf _buf)
    {
        return new GrowthItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 下一阶段
    /// </summary>
    public readonly int? NextState;
    public readonly int PersistentDay;
    public readonly int? AfterPickingState;
   
    public const int __ID__ = 877556122;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Desc:" + Desc + ","
        + "NextState:" + NextState + ","
        + "PersistentDay:" + PersistentDay + ","
        + "AfterPickingState:" + AfterPickingState + ","
        + "}";
    }
}
}

