
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class ItemCount : Luban.BeanBase
{
    public ItemCount(ByteBuf _buf) 
    {
        Item = _buf.ReadInt();
        Item_Ref = null;
        Count = _buf.ReadInt();
    }

    public static ItemCount DeserializeItemCount(ByteBuf _buf)
    {
        return new ItemCount(_buf);
    }

    public readonly int Item;
    public Item Item_Ref;
    public readonly int Count;
   
    public const int __ID__ = -163186276;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Item_Ref = tables.ItemTable.GetOrDefault(Item);
    }

    public override string ToString()
    {
        return "{ "
        + "Item:" + Item + ","
        + "Count:" + Count + ","
        + "}";
    }
}
}

