
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        UIIconName = _buf.ReadString();
        MaxStackCount = _buf.ReadInt();
        if(_buf.ReadBool()){ UesAnimation = _buf.ReadInt(); } else { UesAnimation = null; }
        UesAnimation_Ref = null;
        Quality = (Quality)_buf.ReadInt();
        ItemType = (ItemType)_buf.ReadInt();
        if(_buf.ReadBool()){ Unit = _buf.ReadInt(); } else { Unit = null; }
        Unit_Ref = null;
        {int __n0 = _buf.ReadSize(); AccumulatePower = new int[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { int __e0;__e0 = _buf.ReadInt(); AccumulatePower[__index0] = __e0;}}
    }

    public static Item DeserializeItem(ByteBuf _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// icon
    /// </summary>
    public readonly string UIIconName;
    public readonly int MaxStackCount;
    public readonly int? UesAnimation;
    public AnimationItem UesAnimation_Ref;
    public readonly Quality Quality;
    public readonly ItemType ItemType;
    public readonly int? Unit;
    public UnitItem Unit_Ref;
    public readonly int[] AccumulatePower;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UesAnimation_Ref = UesAnimation!= null ? tables.AnimationTable.GetOrDefault(UesAnimation.Value) : null;
        Unit_Ref = Unit!= null ? tables.UnitTable.GetOrDefault(Unit.Value) : null;
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "UIIconName:" + UIIconName + ","
        + "MaxStackCount:" + MaxStackCount + ","
        + "UesAnimation:" + UesAnimation + ","
        + "Quality:" + Quality + ","
        + "ItemType:" + ItemType + ","
        + "Unit:" + Unit + ","
        + "AccumulatePower:" + Luban.StringUtil.CollectionToString(AccumulatePower) + ","
        + "}";
    }
}
}

