
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GamePlay.Runtime
{ 
    public enum ItemType
    {
        Tool = 0,
        Crop = 1,
        Mat = 2,
        Box = 3,
        Weapon = 4,
        Gem = 5,
        Monster = 6,
        Portal = 7,
    }

} 

