
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public partial class ModelTable
{
    private readonly System.Collections.Generic.Dictionary<int, ModelItem> _dataMap;
    private readonly System.Collections.Generic.List<ModelItem> _dataList;
    
    public ModelTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, ModelItem>(n);
        _dataList = new System.Collections.Generic.List<ModelItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            ModelItem _v;
            _v = global::GamePlay.Runtime.ModelItem.DeserializeModelItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ModelItem> DataMap => _dataMap;
    public System.Collections.Generic.List<ModelItem> DataList => _dataList;

    public ModelItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ModelItem Get(int key) => _dataMap[key];
    public ModelItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

