
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class ModelItem : Luban.BeanBase
{
    public ModelItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Path = _buf.ReadString();
    }

    public static ModelItem DeserializeModelItem(ByteBuf _buf)
    {
        return new ModelItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 模型地址
    /// </summary>
    public readonly string Path;
   
    public const int __ID__ = -6992452;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Path:" + Path + ","
        + "}";
    }
}
}

