
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class OpAward : Luban.BeanBase
{
    public OpAward(ByteBuf _buf) 
    {
        if(_buf.ReadBool()){ Award = _buf.ReadInt(); } else { Award = null; }
        Award_Ref = null;
        Type = (ItemGetType)_buf.ReadInt();
    }

    public static OpAward DeserializeOpAward(ByteBuf _buf)
    {
        return new OpAward(_buf);
    }

    public readonly int? Award;
    public AwardItem Award_Ref;
    public readonly ItemGetType Type;
   
    public const int __ID__ = 368482524;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Award_Ref = Award!= null ? tables.AwardTable.GetOrDefault(Award.Value) : null;
    }

    public override string ToString()
    {
        return "{ "
        + "Award:" + Award + ","
        + "type:" + Type + ","
        + "}";
    }
}
}

