
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GamePlay.Runtime
{ 
    public enum OperatedType
    {
        无 = 0,
        手操 = 1,
        吃 = 2,
        打击 = 3,
        镰 = 4,
        锄 = 5,
        斧 = 6,
        镐 = 7,
        洒水 = 8,
        播种 = 9,
        魔法 = 10,
        利爪 = 11,
        其他 = 12,
    }

} 

