
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GamePlay.Runtime
{ 
    public enum Quality
    {
        White = 0,
        Blue = 1,
        Purple = 2,
        yellow = 3,
        Green = 4,
        Red = 5,
    }

} 

