
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public partial class SynthesisTable
{
    private readonly System.Collections.Generic.Dictionary<int, SynthesisItem> _dataMap;
    private readonly System.Collections.Generic.List<SynthesisItem> _dataList;
    
    public SynthesisTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, SynthesisItem>(n);
        _dataList = new System.Collections.Generic.List<SynthesisItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            SynthesisItem _v;
            _v = global::GamePlay.Runtime.SynthesisItem.DeserializeSynthesisItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SynthesisItem> DataMap => _dataMap;
    public System.Collections.Generic.List<SynthesisItem> DataList => _dataList;

    public SynthesisItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SynthesisItem Get(int key) => _dataMap[key];
    public SynthesisItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

