
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class SynthesisItem : Luban.BeanBase
{
    public SynthesisItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Desc = _buf.ReadString();
        if(_buf.ReadBool()){ SyItem = _buf.ReadInt(); } else { SyItem = null; }
        SyItem_Ref = null;
        {int __n0 = _buf.ReadSize(); Items = new ItemCount[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { ItemCount __e0;__e0 = global::GamePlay.Runtime.ItemCount.DeserializeItemCount(_buf); Items[__index0] = __e0;}}
    }

    public static SynthesisItem DeserializeSynthesisItem(ByteBuf _buf)
    {
        return new SynthesisItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 合成对象
    /// </summary>
    public readonly int? SyItem;
    public Item SyItem_Ref;
    /// <summary>
    /// 需要用的道具
    /// </summary>
    public readonly ItemCount[] Items;
   
    public const int __ID__ = 1471355047;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SyItem_Ref = SyItem!= null ? tables.ItemTable.GetOrDefault(SyItem.Value) : null;
        foreach (var _e in Items) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Desc:" + Desc + ","
        + "SyItem:" + SyItem + ","
        + "Items:" + Luban.StringUtil.CollectionToString(Items) + ","
        + "}";
    }
}
}

