
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GamePlay.Runtime
{
public partial class Tables
{
    public AnimationTable AnimationTable {get; }
    public ItemTable ItemTable {get; }
    public ModelTable ModelTable {get; }
    public AwardTable AwardTable {get; }
    public UnitTable UnitTable {get; }
    public SynthesisTable SynthesisTable {get; }
    public AttributeTable AttributeTable {get; }
    public BehaviorTable BehaviorTable {get; }
    public BattleBehaviorTable BattleBehaviorTable {get; }
    public GrowthTable GrowthTable {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        AnimationTable = new AnimationTable(loader("AnimationTable"));
        ItemTable = new ItemTable(loader("ItemTable"));
        ModelTable = new ModelTable(loader("ModelTable"));
        AwardTable = new AwardTable(loader("BoxTable"));
        UnitTable = new UnitTable(loader("UnitTable"));
        SynthesisTable = new SynthesisTable(loader("SynthesisTable"));
        AttributeTable = new AttributeTable(loader("AttributeTable"));
        BehaviorTable = new BehaviorTable(loader("BehaviorTable"));
        BattleBehaviorTable = new BattleBehaviorTable(loader("BattleBehaviorTable"));
        GrowthTable = new GrowthTable(loader("GrowthTable"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        AnimationTable.ResolveRef(this);
        ItemTable.ResolveRef(this);
        ModelTable.ResolveRef(this);
        AwardTable.ResolveRef(this);
        UnitTable.ResolveRef(this);
        SynthesisTable.ResolveRef(this);
        AttributeTable.ResolveRef(this);
        BehaviorTable.ResolveRef(this);
        BattleBehaviorTable.ResolveRef(this);
        GrowthTable.ResolveRef(this);
    }
}

}
