
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class Transmit : Luban.BeanBase
{
    public Transmit(ByteBuf _buf) 
    {
        IsMap = _buf.ReadBool();
        TransmitId = _buf.ReadInt();
    }

    public static Transmit DeserializeTransmit(ByteBuf _buf)
    {
        return new Transmit(_buf);
    }

    public readonly bool IsMap;
    public readonly int TransmitId;
   
    public const int __ID__ = 1345533648;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "IsMap:" + IsMap + ","
        + "TransmitId:" + TransmitId + ","
        + "}";
    }
}
}

