
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GamePlay.Runtime
{ 
    public enum UnitOpType
    {
        None = 0,
        Attack = 1,
        Use = 2,
        OpenUI = 3,
        Transmit = 4,
    }

} 

