
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public partial class UnitTable
{
    private readonly System.Collections.Generic.Dictionary<int, UnitItem> _dataMap;
    private readonly System.Collections.Generic.List<UnitItem> _dataList;
    
    public UnitTable(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, UnitItem>(n);
        _dataList = new System.Collections.Generic.List<UnitItem>(n);
        for(int i = n ; i > 0 ; --i)
        {
            UnitItem _v;
            _v = global::GamePlay.Runtime.UnitItem.DeserializeUnitItem(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, UnitItem> DataMap => _dataMap;
    public System.Collections.Generic.List<UnitItem> DataList => _dataList;

    public UnitItem GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public UnitItem Get(int key) => _dataMap[key];
    public UnitItem this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

