
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GamePlay.Runtime
{
public sealed partial class UnitItem : Luban.BeanBase
{
    public UnitItem(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Doc = _buf.ReadString();
        Model = _buf.ReadInt();
        Model_Ref = null;
        OperatedItemType = (OperatedType)_buf.ReadInt();
        {int __n0 = _buf.ReadSize(); BeOperated = new BeOperated[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { BeOperated __e0;__e0 = global::GamePlay.Runtime.BeOperated.DeserializeBeOperated(_buf); BeOperated[__index0] = __e0;}}
        if(_buf.ReadBool()){ Attribute = _buf.ReadInt(); } else { Attribute = null; }
        Attribute_Ref = null;
        if(_buf.ReadBool()){ BehaviorTable = _buf.ReadInt(); } else { BehaviorTable = null; }
        BehaviorTable_Ref = null;
    }

    public static UnitItem DeserializeUnitItem(ByteBuf _buf)
    {
        return new UnitItem(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 介绍文字
    /// </summary>
    public readonly string Doc;
    public readonly int Model;
    public ModelItem Model_Ref;
    public readonly OperatedType OperatedItemType;
    /// <summary>
    /// 可被操作的类型数组BeOpAnimation@ResultType@ResultAward@ResultOpenUI
    /// </summary>
    public readonly BeOperated[] BeOperated;
    public readonly int? Attribute;
    public AttributeItem Attribute_Ref;
    public readonly int? BehaviorTable;
    public BehaviorTableItem BehaviorTable_Ref;
   
    public const int __ID__ = -228341033;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Model_Ref = tables.ModelTable.GetOrDefault(Model);
        foreach (var _e in BeOperated) { _e?.ResolveRef(tables); }
        Attribute_Ref = Attribute!= null ? tables.AttributeTable.GetOrDefault(Attribute.Value) : null;
        BehaviorTable_Ref = BehaviorTable!= null ? tables.BehaviorTable.GetOrDefault(BehaviorTable.Value) : null;
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Doc:" + Doc + ","
        + "Model:" + Model + ","
        + "OperatedItemType:" + OperatedItemType + ","
        + "BeOperated:" + Luban.StringUtil.CollectionToString(BeOperated) + ","
        + "Attribute:" + Attribute + ","
        + "BehaviorTable:" + BehaviorTable + ","
        + "}";
    }
}
}

