//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;

namespace Gameplay.Runtime
{
    public class EventSend : Singleton<EventSend>
    {
       
        public void FireTestEvent1(System.String key)
        {
            var allEntity = EventData.Instance.GetEntity(typeof(GXGame.ITestEvent1));
            if (allEntity == null)
            {
                return;
            }
            foreach (var entity in allEntity)
            {
                if (entity.State == IEntity.EntityState.IsRunning)
                {
                    ((GXGame.ITestEvent1) entity).Test(key);
                }
            }
        }
        
    }
}
