//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
namespace GamePlay.Runtime
{
    public static class AutoBindEvent
    {
        public static void AddSystem()
        {
            var  eventData =  EventData.Instance;
            
        }
    }
}
