//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;

public class AutoBindEvent
{
    public void AddSystem()
    {
        var  eventData =  EventData.Instance;
        
    }
}

