//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoAccumulateCropIndex
{
    
  
    public static void AddAccumulateCropIndexExternal(this EffEntity effEntity,System.Int32 param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.AccumulateCropIndex>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.AccumulateCropIndex GetAccumulateCropIndex(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.AccumulateCropIndex>();
    }
    
    public static (bool have, GamePlay.Runtime.AccumulateCropIndex data) GetAccumulateCropIndexWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.AccumulateCropIndex>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.AccumulateCropIndex>());
       else
           return(have,default);
    }
    
    public static void ReactiveAccumulateCropIndex(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.AccumulateCropIndex>.TID, effEntity);
    }      
}