//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
public static class AllCapability {
 
    public static readonly int TotallCapabiltys = Order();
    
    private  static int Order()
    {
        var orderTid =  CapabilityID<GamePlay.Runtime.PlayerEnterCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.CollisionDealWithCapabilty,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.SeekerCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.BehaviorTreeCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.TimeOutDestroyCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.KCCCapability,IFixedUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.CommonMoveCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.FlyCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.DetectionLogoCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.OperatedPlayerStartCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.OperatedStart_PlayerCountdownCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.OperatedStart_MonsterCountDownCapbility,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.OperatedStart_AlwaysDetectionCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.UpdateCollisionDataCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.OperatedDetectionCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.OperatedStart_PlayerAccumulateCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.OperatedExecuteCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.OperatedOverCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.BeAttackBehaviorCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.BeAttackAttenuationStrengthCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.ShowItemQualityCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.BeUseCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.JumpoutHarvestCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.HarvestAbsorbCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.ViewCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.DieCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GamePlay.Runtime.CameraEnterCapability,IUpdateSystem>.TID;
        orderTid =  CapabilityID<GameFrame.Runtime.DestroyCapability,IUpdateSystem>.TID;


       return 28;
    }
}