//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoAssetPathComp
{
    
  
    public static void AddAssetPathCompExternal(this EffEntity effEntity,System.String param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.AssetPathComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.AssetPathComp GetAssetPathComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.AssetPathComp>();
    }
    
     public static bool HaveAssetPathComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.AssetPathComp>();
       return have;
     }  
     
      public static bool TryGetAssetPathComp(this EffEntity effEntity,out GamePlay.Runtime.AssetPathComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.AssetPathComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.AssetPathComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveAssetPathComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.AssetPathComp>.TID, effEntity);
    }      
}