//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoAssetPathComp
{
    
  
    public static void AddAssetPathCompExternal(this EffEntity effEntity,System.String param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.AssetPathComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.AssetPathComp GetAssetPathComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.AssetPathComp>();
    }
    
    public static (bool have, GamePlay.Runtime.AssetPathComp data) GetAssetPathCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.AssetPathComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.AssetPathComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveAssetPathComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.AssetPathComp>.TID, effEntity);
    }      
}