//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoAttrComp
{
    
  
    public static void AddAttrCompExternal(this EffEntity effEntity,GamePlay.Runtime.AttrData param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.AttrComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.AttrComp GetAttrComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.AttrComp>();
    }
    
     public static bool HaveAttrComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.AttrComp>();
       return have;
     }  
     
      public static bool TryGetAttrComp(this EffEntity effEntity,out GamePlay.Runtime.AttrComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.AttrComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.AttrComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveAttrComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.AttrComp>.TID, effEntity);
    }      
}