//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoAttrComp
{
    
  
    public static void AddAttrCompExternal(this EffEntity effEntity,GamePlay.Runtime.AttrData param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.AttrComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.AttrComp GetAttrComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.AttrComp>();
    }
    
    public static (bool have, GamePlay.Runtime.AttrComp data) GetAttrCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.AttrComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.AttrComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveAttrComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.AttrComp>.TID, effEntity);
    }      
}