//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBeAttackFuncComp
{
    
  
    public static void AddBeAttackFuncCompExternal(this EffEntity effEntity,GamePlay.Runtime.BeAttackFuncData param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.BeAttackFuncComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.BeAttackFuncComp GetBeAttackFuncComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.BeAttackFuncComp>();
    }
    
     public static bool HaveBeAttackFuncComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.BeAttackFuncComp>();
       return have;
     }  
     
      public static bool TryGetBeAttackFuncComp(this EffEntity effEntity,out GamePlay.Runtime.BeAttackFuncComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.BeAttackFuncComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.BeAttackFuncComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveBeAttackFuncComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeAttackFuncComp>.TID, effEntity);
    }  
    public static void SetBeAttackFuncCompExternal(this EffEntity effEntity,GamePlay.Runtime.BeAttackFuncData param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.BeAttackFuncComp>();
        data->Set(param);
         ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeAttackFuncComp>.TID, effEntity);
    }
    
    public static void AddOrSetBeAttackFuncCompExternal(this EffEntity effEntity,GamePlay.Runtime.BeAttackFuncData param)
    {
        var have = effEntity.HasComponent<GamePlay.Runtime.BeAttackFuncComp>();
        GamePlay.Runtime.BeAttackFuncComp* p;
        if(!have)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.BeAttackFuncComp>();
           p->Init(param);
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.BeAttackFuncComp>();
           p->Set(param);
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeAttackFuncComp>.TID, effEntity);
        }
    }      
}