//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBeAttackTypeComp
{
    
    public static GamePlay.Runtime.BeAttackTypeComp* AddBeAttackTypeCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.BeAttackTypeComp>();
    }
    
    public static void AddBeAttackTypeComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.BeAttackTypeComp>();
    }
    public static GamePlay.Runtime.BeAttackTypeComp* AddBeAttackTypeCompReturn(this EffEntity effEntity,GamePlay.Runtime.BeAttackType param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.BeAttackTypeComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddBeAttackTypeComp(this EffEntity effEntity,GamePlay.Runtime.BeAttackType param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.BeAttackTypeComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.BeAttackTypeComp GetBeAttackTypeComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.BeAttackTypeComp>();
    }
    
     public static bool HaveBeAttackTypeComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.BeAttackTypeComp>();
       return have;
     }  
     
      public static bool TryGetBeAttackTypeComp(this EffEntity effEntity,out GamePlay.Runtime.BeAttackTypeComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.BeAttackTypeComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.BeAttackTypeComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveBeAttackTypeComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeAttackTypeComp>.TID, effEntity);
    }  
    public static EffEntity SetBeAttackTypeComp(this EffEntity effEntity,GamePlay.Runtime.BeAttackType param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.BeAttackTypeComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeAttackTypeComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetBeAttackTypeComp(this EffEntity effEntity,GamePlay.Runtime.BeAttackType param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.BeAttackTypeComp>();
        GamePlay.Runtime.BeAttackTypeComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.BeAttackTypeComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.BeAttackTypeComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeAttackTypeComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}