//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBehaviorTreeComp
{
    
  
    public static void AddBehaviorTreeCompExternal(this EffEntity effEntity,System.String param)
    {
        var data =  effEntity.AddComponent<GameFrame.Runtime.BehaviorTreeComp>();
        data->Init(param);
    }
          
    public static GameFrame.Runtime.BehaviorTreeComp GetBehaviorTreeComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GameFrame.Runtime.BehaviorTreeComp>();
    }
    
    public static (bool have, GameFrame.Runtime.BehaviorTreeComp data) GetBehaviorTreeCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GameFrame.Runtime.BehaviorTreeComp>();
       if(have)
           return (have,effEntity.GetComponent<GameFrame.Runtime.BehaviorTreeComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveBehaviorTreeComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.BehaviorTreeComp>.TID, effEntity);
    }  
    public static void SetBehaviorTreeCompExternal(this EffEntity effEntity,System.String param)
    {
        var data =  effEntity.AddComponent<GameFrame.Runtime.BehaviorTreeComp>();
        data->Set(param);
         ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.BehaviorTreeComp>.TID, effEntity);
    }
    
    public static void AddOrSetBehaviorTreeCompExternal(this EffEntity effEntity,System.String param)
    {
        var have = effEntity.HasComponent<GameFrame.Runtime.BehaviorTreeComp>();
        GameFrame.Runtime.BehaviorTreeComp* p;
        if(!have)
        {
           p = effEntity.AddComponent<GameFrame.Runtime.BehaviorTreeComp>();
           p->Init(param);
        }else{
           p = effEntity.GetComponentPtr<GameFrame.Runtime.BehaviorTreeComp>();
           p->Set(param);
           ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.BehaviorTreeComp>.TID, effEntity);
        }
    }      
}