//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBehaviorTreeComp
{
    
  
    public static void AddBehaviorTreeCompExternal(this EffEntity effEntity,System.String param)
    {
        var data =  effEntity.AddComponent<GameFrame.Runtime.BehaviorTreeComp>();
        data->Init(param);
    }
          
    public static ref GameFrame.Runtime.BehaviorTreeComp GetBehaviorTreeComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GameFrame.Runtime.BehaviorTreeComp>();
    }
    
     public static bool HaveBehaviorTreeComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GameFrame.Runtime.BehaviorTreeComp>();
       return have;
     }  
     
      public static bool TryGetBehaviorTreeComp(this EffEntity effEntity,out GameFrame.Runtime.BehaviorTreeComp data)
      {
         var have = effEntity.HasComponent<GameFrame.Runtime.BehaviorTreeComp>();
         if(have)
              data =  effEntity.GetComponent<GameFrame.Runtime.BehaviorTreeComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveBehaviorTreeComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.BehaviorTreeComp>.TID, effEntity);
    }  
    public static void SetBehaviorTreeCompExternal(this EffEntity effEntity,System.String param)
    {
        var data =  effEntity.AddComponent<GameFrame.Runtime.BehaviorTreeComp>();
        data->Set(param);
         ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.BehaviorTreeComp>.TID, effEntity);
    }
    
    public static void AddOrSetBehaviorTreeCompExternal(this EffEntity effEntity,System.String param)
    {
        var have = effEntity.HasComponent<GameFrame.Runtime.BehaviorTreeComp>();
        GameFrame.Runtime.BehaviorTreeComp* p;
        if(!have)
        {
           p = effEntity.AddComponent<GameFrame.Runtime.BehaviorTreeComp>();
           p->Init(param);
        }else{
           p = effEntity.GetComponentPtr<GameFrame.Runtime.BehaviorTreeComp>();
           p->Set(param);
           ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.BehaviorTreeComp>.TID, effEntity);
        }
    }      
}