//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBeOperatedIndex
{
    
    public static GamePlay.Runtime.BeOperatedIndex* AddBeOperatedIndexReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.BeOperatedIndex>();
    }
    
    public static void AddBeOperatedIndex(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.BeOperatedIndex>();
    }
    public static GamePlay.Runtime.BeOperatedIndex* AddBeOperatedIndexReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.BeOperatedIndex>();
        p->Value = param;
        return p;
    }
    
    public static void AddBeOperatedIndex(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.BeOperatedIndex>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.BeOperatedIndex GetBeOperatedIndex(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.BeOperatedIndex>();
    }
    
     public static bool HaveBeOperatedIndex(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.BeOperatedIndex>();
       return have;
     }  
     
      public static bool TryGetBeOperatedIndex(this EffEntity effEntity,out GamePlay.Runtime.BeOperatedIndex data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.BeOperatedIndex>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.BeOperatedIndex>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveBeOperatedIndex(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeOperatedIndex>.TID, effEntity);
    }  
    public static EffEntity SetBeOperatedIndex(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.BeOperatedIndex>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeOperatedIndex>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetBeOperatedIndex(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.BeOperatedIndex>();
        GamePlay.Runtime.BeOperatedIndex* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.BeOperatedIndex>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.BeOperatedIndex>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeOperatedIndex>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}