//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBeUseBuffComp
{
    
    public static GamePlay.Runtime.BeUseBuffComp* AddBeUseBuffCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.BeUseBuffComp>();
    }
    
    public static void AddBeUseBuffComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.BeUseBuffComp>();
    }      
    public static GamePlay.Runtime.BeUseBuffComp GetBeUseBuffComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.BeUseBuffComp>();
    }
    
    public static (bool have, GamePlay.Runtime.BeUseBuffComp data) GetBeUseBuffCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.BeUseBuffComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.BeUseBuffComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveBeUseBuffComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BeUseBuffComp>.TID, effEntity);
    }      
}