//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBindingTargetOverComp
{
    
    public static GameFrame.Runtime.BindingTargetOverComp* AddBindingTargetOverCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GameFrame.Runtime.BindingTargetOverComp>();
    }
    
    public static void AddBindingTargetOverComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.BindingTargetOverComp>();
    }      
    public static ref GameFrame.Runtime.BindingTargetOverComp GetBindingTargetOverComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GameFrame.Runtime.BindingTargetOverComp>();
    }
    
     public static bool HaveBindingTargetOverComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GameFrame.Runtime.BindingTargetOverComp>();
       return have;
     }  
     
      public static bool TryGetBindingTargetOverComp(this EffEntity effEntity,out GameFrame.Runtime.BindingTargetOverComp data)
      {
         var have = effEntity.HasComponent<GameFrame.Runtime.BindingTargetOverComp>();
         if(have)
              data =  effEntity.GetComponent<GameFrame.Runtime.BindingTargetOverComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveBindingTargetOverComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.BindingTargetOverComp>.TID, effEntity);
    }      
}