//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBindingTargetOverComp
{
    
    public static GameFrame.Runtime.BindingTargetOverComp* AddBindingTargetOverCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GameFrame.Runtime.BindingTargetOverComp>();
    }
    
    public static void AddBindingTargetOverComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.BindingTargetOverComp>();
    }      
    public static GameFrame.Runtime.BindingTargetOverComp GetBindingTargetOverComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GameFrame.Runtime.BindingTargetOverComp>();
    }
    
    public static (bool have, GameFrame.Runtime.BindingTargetOverComp data) GetBindingTargetOverCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GameFrame.Runtime.BindingTargetOverComp>();
       if(have)
           return (have,effEntity.GetComponent<GameFrame.Runtime.BindingTargetOverComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveBindingTargetOverComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.BindingTargetOverComp>.TID, effEntity);
    }      
}