//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoBodyCollisionLayerComp
{
    
    public static GamePlay.Runtime.BodyCollisionLayerComp* AddBodyCollisionLayerCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.BodyCollisionLayerComp>();
    }
    
    public static void AddBodyCollisionLayerComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.BodyCollisionLayerComp>();
    }
    public static GamePlay.Runtime.BodyCollisionLayerComp* AddBodyCollisionLayerCompReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.BodyCollisionLayerComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddBodyCollisionLayerComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.BodyCollisionLayerComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.BodyCollisionLayerComp GetBodyCollisionLayerComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.BodyCollisionLayerComp>();
    }
    
    public static (bool have, GamePlay.Runtime.BodyCollisionLayerComp data) GetBodyCollisionLayerCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.BodyCollisionLayerComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.BodyCollisionLayerComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveBodyCollisionLayerComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BodyCollisionLayerComp>.TID, effEntity);
    }  
    public static EffEntity SetBodyCollisionLayerComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.BodyCollisionLayerComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BodyCollisionLayerComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetBodyCollisionLayerComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.BodyCollisionLayerComp>();
        GamePlay.Runtime.BodyCollisionLayerComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.BodyCollisionLayerComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.BodyCollisionLayerComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.BodyCollisionLayerComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}