//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoCameraWatcherComp
{
    
    public static GamePlay.Runtime.CameraWatcherComp* AddCameraWatcherCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.CameraWatcherComp>();
    }
    
    public static void AddCameraWatcherComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.CameraWatcherComp>();
    }
    public static GamePlay.Runtime.CameraWatcherComp* AddCameraWatcherCompReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.CameraWatcherComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddCameraWatcherComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.CameraWatcherComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.CameraWatcherComp GetCameraWatcherComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.CameraWatcherComp>();
    }
    
     public static bool HaveCameraWatcherComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.CameraWatcherComp>();
       return have;
     }  
     
      public static bool TryGetCameraWatcherComp(this EffEntity effEntity,out GamePlay.Runtime.CameraWatcherComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.CameraWatcherComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.CameraWatcherComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveCameraWatcherComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CameraWatcherComp>.TID, effEntity);
    }  
    public static EffEntity SetCameraWatcherComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.CameraWatcherComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CameraWatcherComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetCameraWatcherComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.CameraWatcherComp>();
        GamePlay.Runtime.CameraWatcherComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.CameraWatcherComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.CameraWatcherComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CameraWatcherComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}