//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoCameraLensZoomAngleComp
{
    
    public static GamePlay.Runtime.CameraLensZoomAngleComp* AddCameraLensZoomAngleCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.CameraLensZoomAngleComp>();
    }
    
    public static void AddCameraLensZoomAngleComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.CameraLensZoomAngleComp>();
    }
    public static GamePlay.Runtime.CameraLensZoomAngleComp* AddCameraLensZoomAngleCompReturn(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.CameraLensZoomAngleComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddCameraLensZoomAngleComp(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.CameraLensZoomAngleComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.CameraLensZoomAngleComp GetCameraLensZoomAngleComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.CameraLensZoomAngleComp>();
    }
    
    public static (bool have, GamePlay.Runtime.CameraLensZoomAngleComp data) GetCameraLensZoomAngleCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.CameraLensZoomAngleComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.CameraLensZoomAngleComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveCameraLensZoomAngleComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CameraLensZoomAngleComp>.TID, effEntity);
    }  
    public static EffEntity SetCameraLensZoomAngleComp(this EffEntity effEntity,System.Single param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.CameraLensZoomAngleComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CameraLensZoomAngleComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetCameraLensZoomAngleComp(this EffEntity effEntity,System.Single param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.CameraLensZoomAngleComp>();
        GamePlay.Runtime.CameraLensZoomAngleComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.CameraLensZoomAngleComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.CameraLensZoomAngleComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CameraLensZoomAngleComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}