//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoCollisionDetectionDataComp
{
    
    public static GamePlay.Runtime.CollisionDetectionDataComp* AddCollisionDetectionDataCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.CollisionDetectionDataComp>();
    }
    
    public static void AddCollisionDetectionDataComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.CollisionDetectionDataComp>();
    }
    public static GamePlay.Runtime.CollisionDetectionDataComp* AddCollisionDetectionDataCompReturn(this EffEntity effEntity,GamePlay.Runtime.VirtualCollision param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.CollisionDetectionDataComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddCollisionDetectionDataComp(this EffEntity effEntity,GamePlay.Runtime.VirtualCollision param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.CollisionDetectionDataComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.CollisionDetectionDataComp GetCollisionDetectionDataComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.CollisionDetectionDataComp>();
    }
    
    public static (bool have, GamePlay.Runtime.CollisionDetectionDataComp data) GetCollisionDetectionDataCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.CollisionDetectionDataComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.CollisionDetectionDataComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveCollisionDetectionDataComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CollisionDetectionDataComp>.TID, effEntity);
    }  
    public static EffEntity SetCollisionDetectionDataComp(this EffEntity effEntity,GamePlay.Runtime.VirtualCollision param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.CollisionDetectionDataComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CollisionDetectionDataComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetCollisionDetectionDataComp(this EffEntity effEntity,GamePlay.Runtime.VirtualCollision param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.CollisionDetectionDataComp>();
        GamePlay.Runtime.CollisionDetectionDataComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.CollisionDetectionDataComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.CollisionDetectionDataComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CollisionDetectionDataComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}