//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoCollisionMsgComp
{
    
    public static GamePlay.Runtime.CollisionMsgComp* AddCollisionMsgCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.CollisionMsgComp>();
    }
    
    public static void AddCollisionMsgComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.CollisionMsgComp>();
    }
    public static GamePlay.Runtime.CollisionMsgComp* AddCollisionMsgCompReturn(this EffEntity effEntity,GamePlay.Runtime.CollisionMsg param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.CollisionMsgComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddCollisionMsgComp(this EffEntity effEntity,GamePlay.Runtime.CollisionMsg param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.CollisionMsgComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.CollisionMsgComp GetCollisionMsgComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.CollisionMsgComp>();
    }
    
     public static bool HaveCollisionMsgComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.CollisionMsgComp>();
       return have;
     }  
     
      public static bool TryGetCollisionMsgComp(this EffEntity effEntity,out GamePlay.Runtime.CollisionMsgComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.CollisionMsgComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.CollisionMsgComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveCollisionMsgComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CollisionMsgComp>.TID, effEntity);
    }  
    public static EffEntity SetCollisionMsgComp(this EffEntity effEntity,GamePlay.Runtime.CollisionMsg param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.CollisionMsgComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CollisionMsgComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetCollisionMsgComp(this EffEntity effEntity,GamePlay.Runtime.CollisionMsg param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.CollisionMsgComp>();
        GamePlay.Runtime.CollisionMsgComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.CollisionMsgComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.CollisionMsgComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.CollisionMsgComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}