//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoColliderLogicComp
{
    
  
    public static void AddColliderLogicCompExternal(this EffEntity effEntity,GamePlay.Runtime.LogicData param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.ColliderLogicComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.ColliderLogicComp GetColliderLogicComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.ColliderLogicComp>();
    }
    
    public static (bool have, GamePlay.Runtime.ColliderLogicComp data) GetColliderLogicCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.ColliderLogicComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.ColliderLogicComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveColliderLogicComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ColliderLogicComp>.TID, effEntity);
    }      
}