//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoDependEntityComp
{
    
  
    public static void AddDependEntityCompExternal(this EffEntity effEntity,GameFrame.Runtime.EffEntity param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.DependEntityComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.DependEntityComp GetDependEntityComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.DependEntityComp>();
    }
    
    public static (bool have, GamePlay.Runtime.DependEntityComp data) GetDependEntityCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.DependEntityComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.DependEntityComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveDependEntityComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.DependEntityComp>.TID, effEntity);
    }      
}