//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoDependEntityComp
{
    
  
    public static void AddDependEntityCompExternal(this EffEntity effEntity,GameFrame.Runtime.EffEntity param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.DependEntityComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.DependEntityComp GetDependEntityComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.DependEntityComp>();
    }
    
     public static bool HaveDependEntityComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.DependEntityComp>();
       return have;
     }  
     
      public static bool TryGetDependEntityComp(this EffEntity effEntity,out GamePlay.Runtime.DependEntityComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.DependEntityComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.DependEntityComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveDependEntityComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.DependEntityComp>.TID, effEntity);
    }      
}