//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoDestroyComp
{
    
    public static GameFrame.Runtime.DestroyComp* AddDestroyCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GameFrame.Runtime.DestroyComp>();
    }
    
    public static void AddDestroyComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.DestroyComp>();
    }      
    public static ref GameFrame.Runtime.DestroyComp GetDestroyComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GameFrame.Runtime.DestroyComp>();
    }
    
     public static bool HaveDestroyComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GameFrame.Runtime.DestroyComp>();
       return have;
     }  
     
      public static bool TryGetDestroyComp(this EffEntity effEntity,out GameFrame.Runtime.DestroyComp data)
      {
         var have = effEntity.HasComponent<GameFrame.Runtime.DestroyComp>();
         if(have)
              data =  effEntity.GetComponent<GameFrame.Runtime.DestroyComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveDestroyComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.DestroyComp>.TID, effEntity);
    }      
}