//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoDestroyComp
{
    
    public static GameFrame.Runtime.DestroyComp* AddDestroyCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GameFrame.Runtime.DestroyComp>();
    }
    
    public static void AddDestroyComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.DestroyComp>();
    }      
    public static GameFrame.Runtime.DestroyComp GetDestroyComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GameFrame.Runtime.DestroyComp>();
    }
    
    public static (bool have, GameFrame.Runtime.DestroyComp data) GetDestroyCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GameFrame.Runtime.DestroyComp>();
       if(have)
           return (have,effEntity.GetComponent<GameFrame.Runtime.DestroyComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveDestroyComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.DestroyComp>.TID, effEntity);
    }      
}