//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoDieComp
{
    
    public static GameFrame.Runtime.DieComp* AddDieCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GameFrame.Runtime.DieComp>();
    }
    
    public static void AddDieComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.DieComp>();
    }
    public static GameFrame.Runtime.DieComp* AddDieCompReturn(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GameFrame.Runtime.DieComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddDieComp(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GameFrame.Runtime.DieComp>();
        p->Value = param;
    }
          
    public static ref GameFrame.Runtime.DieComp GetDieComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GameFrame.Runtime.DieComp>();
    }
    
     public static bool HaveDieComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GameFrame.Runtime.DieComp>();
       return have;
     }  
     
      public static bool TryGetDieComp(this EffEntity effEntity,out GameFrame.Runtime.DieComp data)
      {
         var have = effEntity.HasComponent<GameFrame.Runtime.DieComp>();
         if(have)
              data =  effEntity.GetComponent<GameFrame.Runtime.DieComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveDieComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.DieComp>.TID, effEntity);
    }  
    public static EffEntity SetDieComp(this EffEntity effEntity,System.Single param)
    {
        var p = effEntity.GetComponentPtr<GameFrame.Runtime.DieComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.DieComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetDieComp(this EffEntity effEntity,System.Single param)
    {
        var has = effEntity.HasComponent<GameFrame.Runtime.DieComp>();
        GameFrame.Runtime.DieComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GameFrame.Runtime.DieComp>();
        }else{
           p = effEntity.GetComponentPtr<GameFrame.Runtime.DieComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.DieComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}