//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoEnterOparatedComp
{
    
    public static GamePlay.Runtime.EnterOparatedComp* AddEnterOparatedCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.EnterOparatedComp>();
    }
    
    public static void AddEnterOparatedComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.EnterOparatedComp>();
    }
    public static GamePlay.Runtime.EnterOparatedComp* AddEnterOparatedCompReturn(this EffEntity effEntity,GamePlay.Runtime.OparatedData param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.EnterOparatedComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddEnterOparatedComp(this EffEntity effEntity,GamePlay.Runtime.OparatedData param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.EnterOparatedComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.EnterOparatedComp GetEnterOparatedComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.EnterOparatedComp>();
    }
    
     public static bool HaveEnterOparatedComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.EnterOparatedComp>();
       return have;
     }  
     
      public static bool TryGetEnterOparatedComp(this EffEntity effEntity,out GamePlay.Runtime.EnterOparatedComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.EnterOparatedComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.EnterOparatedComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveEnterOparatedComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.EnterOparatedComp>.TID, effEntity);
    }  
    public static EffEntity SetEnterOparatedComp(this EffEntity effEntity,GamePlay.Runtime.OparatedData param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.EnterOparatedComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.EnterOparatedComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetEnterOparatedComp(this EffEntity effEntity,GamePlay.Runtime.OparatedData param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.EnterOparatedComp>();
        GamePlay.Runtime.EnterOparatedComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.EnterOparatedComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.EnterOparatedComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.EnterOparatedComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}