//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoFlyComp
{
    
    public static GamePlay.Runtime.FlyComp* AddFlyCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.FlyComp>();
    }
    
    public static void AddFlyComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.FlyComp>();
    }      
    public static ref GamePlay.Runtime.FlyComp GetFlyComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.FlyComp>();
    }
    
     public static bool HaveFlyComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.FlyComp>();
       return have;
     }  
     
      public static bool TryGetFlyComp(this EffEntity effEntity,out GamePlay.Runtime.FlyComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.FlyComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.FlyComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveFlyComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.FlyComp>.TID, effEntity);
    }      
}