//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoForceAnimationComp
{
    
    public static GamePlay.Runtime.ForceAnimationComp* AddForceAnimationCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.ForceAnimationComp>();
    }
    
    public static void AddForceAnimationComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.ForceAnimationComp>();
    }
    public static GamePlay.Runtime.ForceAnimationComp* AddForceAnimationCompReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.ForceAnimationComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddForceAnimationComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.ForceAnimationComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.ForceAnimationComp GetForceAnimationComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.ForceAnimationComp>();
    }
    
    public static (bool have, GamePlay.Runtime.ForceAnimationComp data) GetForceAnimationCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.ForceAnimationComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.ForceAnimationComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveForceAnimationComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ForceAnimationComp>.TID, effEntity);
    }  
    public static EffEntity SetForceAnimationComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.ForceAnimationComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ForceAnimationComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetForceAnimationComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.ForceAnimationComp>();
        GamePlay.Runtime.ForceAnimationComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.ForceAnimationComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.ForceAnimationComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ForceAnimationComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}