//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoGoapActionComponent
{
    
    public static GameFrame.Runtime.GoapActionComponent* AddGoapActionComponentReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GameFrame.Runtime.GoapActionComponent>();
    }
    
    public static void AddGoapActionComponent(this EffEntity effEntity)
    {
        effEntity.AddComponent<GameFrame.Runtime.GoapActionComponent>();
    }
    public static GameFrame.Runtime.GoapActionComponent* AddGoapActionComponentReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GameFrame.Runtime.GoapActionComponent>();
        p->Value = param;
        return p;
    }
    
    public static void AddGoapActionComponent(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GameFrame.Runtime.GoapActionComponent>();
        p->Value = param;
    }
          
    public static GameFrame.Runtime.GoapActionComponent GetGoapActionComponent(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GameFrame.Runtime.GoapActionComponent>();
    }
    
    public static (bool have, GameFrame.Runtime.GoapActionComponent data) GetGoapActionComponentWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GameFrame.Runtime.GoapActionComponent>();
       if(have)
           return (have,effEntity.GetComponent<GameFrame.Runtime.GoapActionComponent>());
       else
           return(have,default);
    }
    
    public static void ReactiveGoapActionComponent(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.GoapActionComponent>.TID, effEntity);
    }  
    public static EffEntity SetGoapActionComponent(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GameFrame.Runtime.GoapActionComponent>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.GoapActionComponent>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetGoapActionComponent(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GameFrame.Runtime.GoapActionComponent>();
        GameFrame.Runtime.GoapActionComponent* p;
        if(!has)
        {
           p = effEntity.AddComponent<GameFrame.Runtime.GoapActionComponent>();
        }else{
           p = effEntity.GetComponentPtr<GameFrame.Runtime.GoapActionComponent>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.GoapActionComponent>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}