//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoGravityDirVectorComp
{
    
    public static GamePlay.Runtime.GravityDirVectorComp* AddGravityDirVectorCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.GravityDirVectorComp>();
    }
    
    public static void AddGravityDirVectorComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.GravityDirVectorComp>();
    }
    public static GamePlay.Runtime.GravityDirVectorComp* AddGravityDirVectorCompReturn(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.GravityDirVectorComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddGravityDirVectorComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.GravityDirVectorComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.GravityDirVectorComp GetGravityDirVectorComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.GravityDirVectorComp>();
    }
    
    public static (bool have, GamePlay.Runtime.GravityDirVectorComp data) GetGravityDirVectorCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.GravityDirVectorComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.GravityDirVectorComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveGravityDirVectorComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GravityDirVectorComp>.TID, effEntity);
    }  
    public static EffEntity SetGravityDirVectorComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.GravityDirVectorComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GravityDirVectorComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetGravityDirVectorComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.GravityDirVectorComp>();
        GamePlay.Runtime.GravityDirVectorComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.GravityDirVectorComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.GravityDirVectorComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GravityDirVectorComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}