//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoGravityAccelerationComp
{
    
    public static GamePlay.Runtime.GravityAccelerationComp* AddGravityAccelerationCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.GravityAccelerationComp>();
    }
    
    public static void AddGravityAccelerationComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.GravityAccelerationComp>();
    }
    public static GamePlay.Runtime.GravityAccelerationComp* AddGravityAccelerationCompReturn(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.GravityAccelerationComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddGravityAccelerationComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.GravityAccelerationComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.GravityAccelerationComp GetGravityAccelerationComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.GravityAccelerationComp>();
    }
    
     public static bool HaveGravityAccelerationComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.GravityAccelerationComp>();
       return have;
     }  
     
      public static bool TryGetGravityAccelerationComp(this EffEntity effEntity,out GamePlay.Runtime.GravityAccelerationComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.GravityAccelerationComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.GravityAccelerationComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveGravityAccelerationComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GravityAccelerationComp>.TID, effEntity);
    }  
    public static EffEntity SetGravityAccelerationComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.GravityAccelerationComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GravityAccelerationComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetGravityAccelerationComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.GravityAccelerationComp>();
        GamePlay.Runtime.GravityAccelerationComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.GravityAccelerationComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.GravityAccelerationComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GravityAccelerationComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}