//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoGroundCollisionComp
{
    
    public static GamePlay.Runtime.GroundCollisionComp* AddGroundCollisionCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.GroundCollisionComp>();
    }
    
    public static void AddGroundCollisionComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.GroundCollisionComp>();
    }
    public static GamePlay.Runtime.GroundCollisionComp* AddGroundCollisionCompReturn(this EffEntity effEntity,GamePlay.Runtime.GroundCollision param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.GroundCollisionComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddGroundCollisionComp(this EffEntity effEntity,GamePlay.Runtime.GroundCollision param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.GroundCollisionComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.GroundCollisionComp GetGroundCollisionComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.GroundCollisionComp>();
    }
    
    public static (bool have, GamePlay.Runtime.GroundCollisionComp data) GetGroundCollisionCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.GroundCollisionComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.GroundCollisionComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveGroundCollisionComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GroundCollisionComp>.TID, effEntity);
    }  
    public static EffEntity SetGroundCollisionComp(this EffEntity effEntity,GamePlay.Runtime.GroundCollision param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.GroundCollisionComp>();
        p->Value = param;
        if (p->Equatable(param))
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GroundCollisionComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetGroundCollisionComp(this EffEntity effEntity,GamePlay.Runtime.GroundCollision param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.GroundCollisionComp>();
        GamePlay.Runtime.GroundCollisionComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.GroundCollisionComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.GroundCollisionComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.GroundCollisionComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}