//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoHarvestStateComp
{
    
    public static GamePlay.Runtime.HarvestStateComp* AddHarvestStateCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.HarvestStateComp>();
    }
    
    public static void AddHarvestStateComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.HarvestStateComp>();
    }
    public static GamePlay.Runtime.HarvestStateComp* AddHarvestStateCompReturn(this EffEntity effEntity,GamePlay.Runtime.HarvestState param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.HarvestStateComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddHarvestStateComp(this EffEntity effEntity,GamePlay.Runtime.HarvestState param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.HarvestStateComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.HarvestStateComp GetHarvestStateComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.HarvestStateComp>();
    }
    
    public static (bool have, GamePlay.Runtime.HarvestStateComp data) GetHarvestStateCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.HarvestStateComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.HarvestStateComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveHarvestStateComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.HarvestStateComp>.TID, effEntity);
    }  
    public static EffEntity SetHarvestStateComp(this EffEntity effEntity,GamePlay.Runtime.HarvestState param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.HarvestStateComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.HarvestStateComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetHarvestStateComp(this EffEntity effEntity,GamePlay.Runtime.HarvestState param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.HarvestStateComp>();
        GamePlay.Runtime.HarvestStateComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.HarvestStateComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.HarvestStateComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.HarvestStateComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}