//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoHPComp
{
    
    public static GamePlay.Runtime.HPComp* AddHPCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.HPComp>();
    }
    
    public static void AddHPComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.HPComp>();
    }
    public static GamePlay.Runtime.HPComp* AddHPCompReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.HPComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddHPComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.HPComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.HPComp GetHPComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.HPComp>();
    }
    
     public static bool HaveHPComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.HPComp>();
       return have;
     }  
     
      public static bool TryGetHPComp(this EffEntity effEntity,out GamePlay.Runtime.HPComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.HPComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.HPComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveHPComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.HPComp>.TID, effEntity);
    }  
    public static EffEntity SetHPComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.HPComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.HPComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetHPComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.HPComp>();
        GamePlay.Runtime.HPComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.HPComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.HPComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.HPComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}