//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoItemComp
{
    
  
    public static void AddItemCompExternal(this EffEntity effEntity,GamePlay.Runtime.Item param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.ItemComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.ItemComp GetItemComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.ItemComp>();
    }
    
    public static (bool have, GamePlay.Runtime.ItemComp data) GetItemCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.ItemComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.ItemComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveItemComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemComp>.TID, effEntity);
    }  
    public static EffEntity SetItemComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.ItemComp>();
        p->valueIndex = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetItemComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.ItemComp>();
        GamePlay.Runtime.ItemComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.ItemComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.ItemComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemComp>.TID, effEntity);
        }
        p->valueIndex = param;
        return effEntity;
    }      
}