//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoItemCountComp
{
    
    public static GamePlay.Runtime.ItemCountComp* AddItemCountCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
    }
    
    public static void AddItemCountComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
    }
    public static GamePlay.Runtime.ItemCountComp* AddItemCountCompReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddItemCountComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.ItemCountComp GetItemCountComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.ItemCountComp>();
    }
    
    public static (bool have, GamePlay.Runtime.ItemCountComp data) GetItemCountCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.ItemCountComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.ItemCountComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveItemCountComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemCountComp>.TID, effEntity);
    }  
    public static EffEntity SetItemCountComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.ItemCountComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemCountComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetItemCountComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.ItemCountComp>();
        GamePlay.Runtime.ItemCountComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.ItemCountComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemCountComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}