//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoItemCountComp
{
    
    public static GamePlay.Runtime.ItemCountComp* AddItemCountCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
    }
    
    public static void AddItemCountComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
    }
    public static GamePlay.Runtime.ItemCountComp* AddItemCountCompReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddItemCountComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.ItemCountComp GetItemCountComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.ItemCountComp>();
    }
    
     public static bool HaveItemCountComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.ItemCountComp>();
       return have;
     }  
     
      public static bool TryGetItemCountComp(this EffEntity effEntity,out GamePlay.Runtime.ItemCountComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.ItemCountComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.ItemCountComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveItemCountComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemCountComp>.TID, effEntity);
    }  
    public static EffEntity SetItemCountComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.ItemCountComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemCountComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetItemCountComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.ItemCountComp>();
        GamePlay.Runtime.ItemCountComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.ItemCountComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.ItemCountComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ItemCountComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}