//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoJumpSpeedComp
{
    
    public static GamePlay.Runtime.JumpSpeedComp* AddJumpSpeedCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.JumpSpeedComp>();
    }
    
    public static void AddJumpSpeedComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.JumpSpeedComp>();
    }
    public static GamePlay.Runtime.JumpSpeedComp* AddJumpSpeedCompReturn(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.JumpSpeedComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddJumpSpeedComp(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.JumpSpeedComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.JumpSpeedComp GetJumpSpeedComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.JumpSpeedComp>();
    }
    
     public static bool HaveJumpSpeedComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.JumpSpeedComp>();
       return have;
     }  
     
      public static bool TryGetJumpSpeedComp(this EffEntity effEntity,out GamePlay.Runtime.JumpSpeedComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.JumpSpeedComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.JumpSpeedComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveJumpSpeedComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.JumpSpeedComp>.TID, effEntity);
    }  
    public static EffEntity SetJumpSpeedComp(this EffEntity effEntity,System.Single param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.JumpSpeedComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.JumpSpeedComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetJumpSpeedComp(this EffEntity effEntity,System.Single param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.JumpSpeedComp>();
        GamePlay.Runtime.JumpSpeedComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.JumpSpeedComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.JumpSpeedComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.JumpSpeedComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}