//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoMoveDirectionComp
{
    
    public static GamePlay.Runtime.MoveDirectionComp* AddMoveDirectionCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.MoveDirectionComp>();
    }
    
    public static void AddMoveDirectionComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.MoveDirectionComp>();
    }
    public static GamePlay.Runtime.MoveDirectionComp* AddMoveDirectionCompReturn(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.MoveDirectionComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddMoveDirectionComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.MoveDirectionComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.MoveDirectionComp GetMoveDirectionComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.MoveDirectionComp>();
    }
    
    public static (bool have, GamePlay.Runtime.MoveDirectionComp data) GetMoveDirectionCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.MoveDirectionComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.MoveDirectionComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveMoveDirectionComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.MoveDirectionComp>.TID, effEntity);
    }  
    public static EffEntity SetMoveDirectionComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.MoveDirectionComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.MoveDirectionComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetMoveDirectionComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.MoveDirectionComp>();
        GamePlay.Runtime.MoveDirectionComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.MoveDirectionComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.MoveDirectionComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.MoveDirectionComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}