//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoMoveDirectionExPowerComp
{
    
    public static GamePlay.Runtime.MoveDirectionExPowerComp* AddMoveDirectionExPowerCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.MoveDirectionExPowerComp>();
    }
    
    public static void AddMoveDirectionExPowerComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.MoveDirectionExPowerComp>();
    }
    public static GamePlay.Runtime.MoveDirectionExPowerComp* AddMoveDirectionExPowerCompReturn(this EffEntity effEntity,GamePlay.Runtime.MoveDirectionExPowerData param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.MoveDirectionExPowerComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddMoveDirectionExPowerComp(this EffEntity effEntity,GamePlay.Runtime.MoveDirectionExPowerData param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.MoveDirectionExPowerComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.MoveDirectionExPowerComp GetMoveDirectionExPowerComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.MoveDirectionExPowerComp>();
    }
    
    public static (bool have, GamePlay.Runtime.MoveDirectionExPowerComp data) GetMoveDirectionExPowerCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.MoveDirectionExPowerComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.MoveDirectionExPowerComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveMoveDirectionExPowerComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.MoveDirectionExPowerComp>.TID, effEntity);
    }  
    public static EffEntity SetMoveDirectionExPowerComp(this EffEntity effEntity,GamePlay.Runtime.MoveDirectionExPowerData param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.MoveDirectionExPowerComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.MoveDirectionExPowerComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetMoveDirectionExPowerComp(this EffEntity effEntity,GamePlay.Runtime.MoveDirectionExPowerData param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.MoveDirectionExPowerComp>();
        GamePlay.Runtime.MoveDirectionExPowerComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.MoveDirectionExPowerComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.MoveDirectionExPowerComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.MoveDirectionExPowerComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}