//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoObjectComp
{
    
  
    public static void AddObjectCompExternal(this EffEntity effEntity,System.Object param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.ObjectComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.ObjectComp GetObjectComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.ObjectComp>();
    }
    
     public static bool HaveObjectComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.ObjectComp>();
       return have;
     }  
     
      public static bool TryGetObjectComp(this EffEntity effEntity,out GamePlay.Runtime.ObjectComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.ObjectComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.ObjectComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveObjectComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ObjectComp>.TID, effEntity);
    }      
}