//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoObjectComp
{
    
  
    public static void AddObjectCompExternal(this EffEntity effEntity,System.Object param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.ObjectComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.ObjectComp GetObjectComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.ObjectComp>();
    }
    
    public static (bool have, GamePlay.Runtime.ObjectComp data) GetObjectCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.ObjectComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.ObjectComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveObjectComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ObjectComp>.TID, effEntity);
    }      
}