//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoOperatedDetectionComp
{
    
    public static GamePlay.Runtime.OperatedDetectionComp* AddOperatedDetectionCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionComp>();
    }
    
    public static void AddOperatedDetectionComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionComp>();
    }
    public static GamePlay.Runtime.OperatedDetectionComp* AddOperatedDetectionCompReturn(this EffEntity effEntity,GamePlay.Runtime.OperatedDetectionData param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddOperatedDetectionComp(this EffEntity effEntity,GamePlay.Runtime.OperatedDetectionData param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.OperatedDetectionComp GetOperatedDetectionComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.OperatedDetectionComp>();
    }
    
     public static bool HaveOperatedDetectionComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.OperatedDetectionComp>();
       return have;
     }  
     
      public static bool TryGetOperatedDetectionComp(this EffEntity effEntity,out GamePlay.Runtime.OperatedDetectionComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.OperatedDetectionComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.OperatedDetectionComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveOperatedDetectionComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedDetectionComp>.TID, effEntity);
    }  
    public static EffEntity SetOperatedDetectionComp(this EffEntity effEntity,GamePlay.Runtime.OperatedDetectionData param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedDetectionComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedDetectionComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetOperatedDetectionComp(this EffEntity effEntity,GamePlay.Runtime.OperatedDetectionData param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.OperatedDetectionComp>();
        GamePlay.Runtime.OperatedDetectionComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedDetectionComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedDetectionComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}