//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoOperatedAccumulateComp
{
    
    public static GamePlay.Runtime.OperatedAccumulateComp* AddOperatedAccumulateCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.OperatedAccumulateComp>();
    }
    
    public static void AddOperatedAccumulateComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.OperatedAccumulateComp>();
    }
    public static GamePlay.Runtime.OperatedAccumulateComp* AddOperatedAccumulateCompReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.OperatedAccumulateComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddOperatedAccumulateComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.OperatedAccumulateComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.OperatedAccumulateComp GetOperatedAccumulateComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.OperatedAccumulateComp>();
    }
    
     public static bool HaveOperatedAccumulateComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.OperatedAccumulateComp>();
       return have;
     }  
     
      public static bool TryGetOperatedAccumulateComp(this EffEntity effEntity,out GamePlay.Runtime.OperatedAccumulateComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.OperatedAccumulateComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.OperatedAccumulateComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveOperatedAccumulateComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedAccumulateComp>.TID, effEntity);
    }  
    public static EffEntity SetOperatedAccumulateComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedAccumulateComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedAccumulateComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetOperatedAccumulateComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.OperatedAccumulateComp>();
        GamePlay.Runtime.OperatedAccumulateComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.OperatedAccumulateComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedAccumulateComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedAccumulateComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}