//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoOperatedObjectComp
{
    
  
    public static void AddOperatedObjectCompExternal(this EffEntity effEntity,System.Int32 param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.OperatedObjectComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.OperatedObjectComp GetOperatedObjectComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.OperatedObjectComp>();
    }
    
    public static (bool have, GamePlay.Runtime.OperatedObjectComp data) GetOperatedObjectCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.OperatedObjectComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.OperatedObjectComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveOperatedObjectComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedObjectComp>.TID, effEntity);
    }      
}