//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoOperatedDetectionFilterComp
{
    
    public static GamePlay.Runtime.OperatedDetectionFilterComp* AddOperatedDetectionFilterCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionFilterComp>();
    }
    
    public static void AddOperatedDetectionFilterComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionFilterComp>();
    }
    public static GamePlay.Runtime.OperatedDetectionFilterComp* AddOperatedDetectionFilterCompReturn(this EffEntity effEntity,GamePlay.Runtime.DetectionFilter param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionFilterComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddOperatedDetectionFilterComp(this EffEntity effEntity,GamePlay.Runtime.DetectionFilter param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionFilterComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.OperatedDetectionFilterComp GetOperatedDetectionFilterComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.OperatedDetectionFilterComp>();
    }
    
    public static (bool have, GamePlay.Runtime.OperatedDetectionFilterComp data) GetOperatedDetectionFilterCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.OperatedDetectionFilterComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.OperatedDetectionFilterComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveOperatedDetectionFilterComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedDetectionFilterComp>.TID, effEntity);
    }  
    public static EffEntity SetOperatedDetectionFilterComp(this EffEntity effEntity,GamePlay.Runtime.DetectionFilter param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedDetectionFilterComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedDetectionFilterComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetOperatedDetectionFilterComp(this EffEntity effEntity,GamePlay.Runtime.DetectionFilter param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.OperatedDetectionFilterComp>();
        GamePlay.Runtime.OperatedDetectionFilterComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.OperatedDetectionFilterComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedDetectionFilterComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedDetectionFilterComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}