//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoOperatedObjectComp
{
    
  
    public static void AddOperatedObjectCompExternal(this EffEntity effEntity,System.Int32 param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.OperatedObjectComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.OperatedObjectComp GetOperatedObjectComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.OperatedObjectComp>();
    }
    
     public static bool HaveOperatedObjectComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.OperatedObjectComp>();
       return have;
     }  
     
      public static bool TryGetOperatedObjectComp(this EffEntity effEntity,out GamePlay.Runtime.OperatedObjectComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.OperatedObjectComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.OperatedObjectComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveOperatedObjectComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedObjectComp>.TID, effEntity);
    }      
}