//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoOperatedCountdownComp
{
    
    public static GamePlay.Runtime.OperatedCountdownComp* AddOperatedCountdownCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.OperatedCountdownComp>();
    }
    
    public static void AddOperatedCountdownComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.OperatedCountdownComp>();
    }
    public static GamePlay.Runtime.OperatedCountdownComp* AddOperatedCountdownCompReturn(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.OperatedCountdownComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddOperatedCountdownComp(this EffEntity effEntity,System.Int32 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.OperatedCountdownComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.OperatedCountdownComp GetOperatedCountdownComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.OperatedCountdownComp>();
    }
    
    public static (bool have, GamePlay.Runtime.OperatedCountdownComp data) GetOperatedCountdownCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.OperatedCountdownComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.OperatedCountdownComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveOperatedCountdownComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedCountdownComp>.TID, effEntity);
    }  
    public static EffEntity SetOperatedCountdownComp(this EffEntity effEntity,System.Int32 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedCountdownComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedCountdownComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetOperatedCountdownComp(this EffEntity effEntity,System.Int32 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.OperatedCountdownComp>();
        GamePlay.Runtime.OperatedCountdownComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.OperatedCountdownComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedCountdownComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedCountdownComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}