//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoOperatedFuncComp
{
    
  
    public static void AddOperatedFuncCompExternal(this EffEntity effEntity,System.Action<GameFrame.Runtime.EffEntity, GameFrame.Runtime.ECCWorld> param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.OperatedFuncComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.OperatedFuncComp GetOperatedFuncComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.OperatedFuncComp>();
    }
    
    public static (bool have, GamePlay.Runtime.OperatedFuncComp data) GetOperatedFuncCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.OperatedFuncComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.OperatedFuncComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveOperatedFuncComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedFuncComp>.TID, effEntity);
    }  
    public static void SetOperatedFuncCompExternal(this EffEntity effEntity,System.Action<GameFrame.Runtime.EffEntity, GameFrame.Runtime.ECCWorld> param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.OperatedFuncComp>();
        data->Set(param);
         ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedFuncComp>.TID, effEntity);
    }
    
    public static void AddOrSetOperatedFuncCompExternal(this EffEntity effEntity,System.Action<GameFrame.Runtime.EffEntity, GameFrame.Runtime.ECCWorld> param)
    {
        var have = effEntity.HasComponent<GamePlay.Runtime.OperatedFuncComp>();
        GamePlay.Runtime.OperatedFuncComp* p;
        if(!have)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.OperatedFuncComp>();
           p->Init(param);
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedFuncComp>();
           p->Set(param);
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedFuncComp>.TID, effEntity);
        }
    }      
}