//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoOperatedEffectFuncComp
{
    
  
    public static void AddOperatedEffectFuncCompExternal(this EffEntity effEntity,System.Func<GameFrame.Runtime.EffEntity, GameFrame.Runtime.EffEntity, System.Boolean> param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.OperatedEffectFuncComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.OperatedEffectFuncComp GetOperatedEffectFuncComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.OperatedEffectFuncComp>();
    }
    
     public static bool HaveOperatedEffectFuncComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.OperatedEffectFuncComp>();
       return have;
     }  
     
      public static bool TryGetOperatedEffectFuncComp(this EffEntity effEntity,out GamePlay.Runtime.OperatedEffectFuncComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.OperatedEffectFuncComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.OperatedEffectFuncComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveOperatedEffectFuncComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedEffectFuncComp>.TID, effEntity);
    }  
    public static void SetOperatedEffectFuncCompExternal(this EffEntity effEntity,System.Func<GameFrame.Runtime.EffEntity, GameFrame.Runtime.EffEntity, System.Boolean> param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.OperatedEffectFuncComp>();
        data->Set(param);
         ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedEffectFuncComp>.TID, effEntity);
    }
    
    public static void AddOrSetOperatedEffectFuncCompExternal(this EffEntity effEntity,System.Func<GameFrame.Runtime.EffEntity, GameFrame.Runtime.EffEntity, System.Boolean> param)
    {
        var have = effEntity.HasComponent<GamePlay.Runtime.OperatedEffectFuncComp>();
        GamePlay.Runtime.OperatedEffectFuncComp* p;
        if(!have)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.OperatedEffectFuncComp>();
           p->Init(param);
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.OperatedEffectFuncComp>();
           p->Set(param);
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.OperatedEffectFuncComp>.TID, effEntity);
        }
    }      
}