//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoPreviousGroundComp
{
    
  
    public static void AddPreviousGroundCompExternal(this EffEntity effEntity,GamePlay.Runtime.PreviousGroundMsg param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.PreviousGroundComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.PreviousGroundComp GetPreviousGroundComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.PreviousGroundComp>();
    }
    
     public static bool HavePreviousGroundComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.PreviousGroundComp>();
       return have;
     }  
     
      public static bool TryGetPreviousGroundComp(this EffEntity effEntity,out GamePlay.Runtime.PreviousGroundComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.PreviousGroundComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.PreviousGroundComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactivePreviousGroundComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.PreviousGroundComp>.TID, effEntity);
    }      
}