//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoPreviousGroundComp
{
    
  
    public static void AddPreviousGroundCompExternal(this EffEntity effEntity,GamePlay.Runtime.PreviousGroundMsg param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.PreviousGroundComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.PreviousGroundComp GetPreviousGroundComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.PreviousGroundComp>();
    }
    
    public static (bool have, GamePlay.Runtime.PreviousGroundComp data) GetPreviousGroundCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.PreviousGroundComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.PreviousGroundComp>());
       else
           return(have,default);
    }
    
    public static void ReactivePreviousGroundComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.PreviousGroundComp>.TID, effEntity);
    }      
}