//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoRunSpeedUpComp
{
    
    public static GamePlay.Runtime.RunSpeedUpComp* AddRunSpeedUpCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.RunSpeedUpComp>();
    }
    
    public static void AddRunSpeedUpComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.RunSpeedUpComp>();
    }
    public static GamePlay.Runtime.RunSpeedUpComp* AddRunSpeedUpCompReturn(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.RunSpeedUpComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddRunSpeedUpComp(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.RunSpeedUpComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.RunSpeedUpComp GetRunSpeedUpComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.RunSpeedUpComp>();
    }
    
    public static (bool have, GamePlay.Runtime.RunSpeedUpComp data) GetRunSpeedUpCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.RunSpeedUpComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.RunSpeedUpComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveRunSpeedUpComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.RunSpeedUpComp>.TID, effEntity);
    }  
    public static EffEntity SetRunSpeedUpComp(this EffEntity effEntity,System.Single param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.RunSpeedUpComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.RunSpeedUpComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetRunSpeedUpComp(this EffEntity effEntity,System.Single param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.RunSpeedUpComp>();
        GamePlay.Runtime.RunSpeedUpComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.RunSpeedUpComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.RunSpeedUpComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.RunSpeedUpComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}