//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoStopMoveDirection
{
    
    public static GamePlay.Runtime.StopMoveDirection* AddStopMoveDirectionReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.StopMoveDirection>();
    }
    
    public static void AddStopMoveDirection(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.StopMoveDirection>();
    }      
    public static GamePlay.Runtime.StopMoveDirection GetStopMoveDirection(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.StopMoveDirection>();
    }
    
    public static (bool have, GamePlay.Runtime.StopMoveDirection data) GetStopMoveDirectionWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.StopMoveDirection>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.StopMoveDirection>());
       else
           return(have,default);
    }
    
    public static void ReactiveStopMoveDirection(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.StopMoveDirection>.TID, effEntity);
    }      
}