//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoThrowComp
{
    
    public static GamePlay.Runtime.ThrowComp* AddThrowCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.ThrowComp>();
    }
    
    public static void AddThrowComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.ThrowComp>();
    }
    public static GamePlay.Runtime.ThrowComp* AddThrowCompReturn(this EffEntity effEntity,System.Boolean param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.ThrowComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddThrowComp(this EffEntity effEntity,System.Boolean param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.ThrowComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.ThrowComp GetThrowComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.ThrowComp>();
    }
    
     public static bool HaveThrowComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.ThrowComp>();
       return have;
     }  
     
      public static bool TryGetThrowComp(this EffEntity effEntity,out GamePlay.Runtime.ThrowComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.ThrowComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.ThrowComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveThrowComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ThrowComp>.TID, effEntity);
    }  
    public static EffEntity SetThrowComp(this EffEntity effEntity,System.Boolean param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.ThrowComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ThrowComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetThrowComp(this EffEntity effEntity,System.Boolean param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.ThrowComp>();
        GamePlay.Runtime.ThrowComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.ThrowComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.ThrowComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.ThrowComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}