//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoTimeOutDestroyComp
{
    
    public static GamePlay.Runtime.TimeOutDestroyComp* AddTimeOutDestroyCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.TimeOutDestroyComp>();
    }
    
    public static void AddTimeOutDestroyComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.TimeOutDestroyComp>();
    }
    public static GamePlay.Runtime.TimeOutDestroyComp* AddTimeOutDestroyCompReturn(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.TimeOutDestroyComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddTimeOutDestroyComp(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.TimeOutDestroyComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.TimeOutDestroyComp GetTimeOutDestroyComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.TimeOutDestroyComp>();
    }
    
     public static bool HaveTimeOutDestroyComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.TimeOutDestroyComp>();
       return have;
     }  
     
      public static bool TryGetTimeOutDestroyComp(this EffEntity effEntity,out GamePlay.Runtime.TimeOutDestroyComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.TimeOutDestroyComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.TimeOutDestroyComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveTimeOutDestroyComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TimeOutDestroyComp>.TID, effEntity);
    }  
    public static EffEntity SetTimeOutDestroyComp(this EffEntity effEntity,System.Single param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.TimeOutDestroyComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TimeOutDestroyComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetTimeOutDestroyComp(this EffEntity effEntity,System.Single param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.TimeOutDestroyComp>();
        GamePlay.Runtime.TimeOutDestroyComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.TimeOutDestroyComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.TimeOutDestroyComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TimeOutDestroyComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}