//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoTurnDirectionComp
{
    
    public static GamePlay.Runtime.TurnDirectionComp* AddTurnDirectionCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.TurnDirectionComp>();
    }
    
    public static void AddTurnDirectionComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.TurnDirectionComp>();
    }
    public static GamePlay.Runtime.TurnDirectionComp* AddTurnDirectionCompReturn(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.TurnDirectionComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddTurnDirectionComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.TurnDirectionComp>();
        p->Value = param;
    }
          
    public static ref GamePlay.Runtime.TurnDirectionComp GetTurnDirectionComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.TurnDirectionComp>();
    }
    
     public static bool HaveTurnDirectionComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.TurnDirectionComp>();
       return have;
     }  
     
      public static bool TryGetTurnDirectionComp(this EffEntity effEntity,out GamePlay.Runtime.TurnDirectionComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.TurnDirectionComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.TurnDirectionComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveTurnDirectionComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TurnDirectionComp>.TID, effEntity);
    }  
    public static EffEntity SetTurnDirectionComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.TurnDirectionComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TurnDirectionComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetTurnDirectionComp(this EffEntity effEntity,UnityEngine.Vector3 param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.TurnDirectionComp>();
        GamePlay.Runtime.TurnDirectionComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.TurnDirectionComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.TurnDirectionComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TurnDirectionComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}