//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoTurnDirectionSpeedComp
{
    
    public static GamePlay.Runtime.TurnDirectionSpeedComp* AddTurnDirectionSpeedCompReturn(this EffEntity effEntity)
    {
        return effEntity.AddComponent<GamePlay.Runtime.TurnDirectionSpeedComp>();
    }
    
    public static void AddTurnDirectionSpeedComp(this EffEntity effEntity)
    {
        effEntity.AddComponent<GamePlay.Runtime.TurnDirectionSpeedComp>();
    }
    public static GamePlay.Runtime.TurnDirectionSpeedComp* AddTurnDirectionSpeedCompReturn(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.TurnDirectionSpeedComp>();
        p->Value = param;
        return p;
    }
    
    public static void AddTurnDirectionSpeedComp(this EffEntity effEntity,System.Single param)
    {
        var p  =  effEntity.AddComponent<GamePlay.Runtime.TurnDirectionSpeedComp>();
        p->Value = param;
    }
          
    public static GamePlay.Runtime.TurnDirectionSpeedComp GetTurnDirectionSpeedComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.TurnDirectionSpeedComp>();
    }
    
    public static (bool have, GamePlay.Runtime.TurnDirectionSpeedComp data) GetTurnDirectionSpeedCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.TurnDirectionSpeedComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.TurnDirectionSpeedComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveTurnDirectionSpeedComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TurnDirectionSpeedComp>.TID, effEntity);
    }  
    public static EffEntity SetTurnDirectionSpeedComp(this EffEntity effEntity,System.Single param)
    {
        var p = effEntity.GetComponentPtr<GamePlay.Runtime.TurnDirectionSpeedComp>();
        p->Value = param;
        
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TurnDirectionSpeedComp>.TID, effEntity);
        return effEntity;
    }
    
    public static EffEntity AddOrSetTurnDirectionSpeedComp(this EffEntity effEntity,System.Single param)
    {
        var has = effEntity.HasComponent<GamePlay.Runtime.TurnDirectionSpeedComp>();
        GamePlay.Runtime.TurnDirectionSpeedComp* p;
        if(!has)
        {
           p = effEntity.AddComponent<GamePlay.Runtime.TurnDirectionSpeedComp>();
        }else{
           p = effEntity.GetComponentPtr<GamePlay.Runtime.TurnDirectionSpeedComp>();
           ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.TurnDirectionSpeedComp>.TID, effEntity);
        }
        p->Value = param;
        return effEntity;
    }      
}