//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoUnitDataComp
{
    
  
    public static void AddUnitDataCompExternal(this EffEntity effEntity,GamePlay.Runtime.UnitData param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.UnitDataComp>();
        data->Init(param);
    }
          
    public static GamePlay.Runtime.UnitDataComp GetUnitDataComp(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GamePlay.Runtime.UnitDataComp>();
    }
    
    public static (bool have, GamePlay.Runtime.UnitDataComp data) GetUnitDataCompWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GamePlay.Runtime.UnitDataComp>();
       if(have)
           return (have,effEntity.GetComponent<GamePlay.Runtime.UnitDataComp>());
       else
           return(have,default);
    }
    
    public static void ReactiveUnitDataComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.UnitDataComp>.TID, effEntity);
    }      
}