//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoUnitDataComp
{
    
  
    public static void AddUnitDataCompExternal(this EffEntity effEntity,GamePlay.Runtime.UnitData param)
    {
        var data =  effEntity.AddComponent<GamePlay.Runtime.UnitDataComp>();
        data->Init(param);
    }
          
    public static ref GamePlay.Runtime.UnitDataComp GetUnitDataComp(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GamePlay.Runtime.UnitDataComp>();
    }
    
     public static bool HaveUnitDataComp(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GamePlay.Runtime.UnitDataComp>();
       return have;
     }  
     
      public static bool TryGetUnitDataComp(this EffEntity effEntity,out GamePlay.Runtime.UnitDataComp data)
      {
         var have = effEntity.HasComponent<GamePlay.Runtime.UnitDataComp>();
         if(have)
              data =  effEntity.GetComponent<GamePlay.Runtime.UnitDataComp>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveUnitDataComp(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GamePlay.Runtime.UnitDataComp>.TID, effEntity);
    }      
}