//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoView
{
    
  
    public static void AddViewExternal(this EffEntity effEntity,GameFrame.Runtime.EffEntityView param)
    {
        var data =  effEntity.AddComponent<GameFrame.Runtime.View>();
        data->Init(param);
    }
          
    public static GameFrame.Runtime.View GetView(this EffEntity effEntity)
    {
        return effEntity.GetComponent<GameFrame.Runtime.View>();
    }
    
    public static (bool have, GameFrame.Runtime.View data) GetViewWithHave(this EffEntity effEntity)
    {
       var have = effEntity.HasComponent<GameFrame.Runtime.View>();
       if(have)
           return (have,effEntity.GetComponent<GameFrame.Runtime.View>());
       else
           return(have,default);
    }
    
    public static void ReactiveView(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.View>.TID, effEntity);
    }      
}