//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
using UnityEngine;
public unsafe static partial class AutoView
{
    
  
    public static void AddViewExternal(this EffEntity effEntity,GameFrame.Runtime.EffEntityView param)
    {
        var data =  effEntity.AddComponent<GameFrame.Runtime.View>();
        data->Init(param);
    }
          
    public static ref GameFrame.Runtime.View GetView(this EffEntity effEntity)
    {
        return ref effEntity.GetComponent<GameFrame.Runtime.View>();
    }
    
     public static bool HaveView(this EffEntity effEntity)
     {
       var have = effEntity.HasComponent<GameFrame.Runtime.View>();
       return have;
     }  
     
      public static bool TryGetView(this EffEntity effEntity,out GameFrame.Runtime.View data)
      {
         var have = effEntity.HasComponent<GameFrame.Runtime.View>();
         if(have)
              data =  effEntity.GetComponent<GameFrame.Runtime.View>();
         else
              data = default;
         return have;
      }   
    
    public static void ReactiveView(this EffEntity effEntity)
    {
        ((World)effEntity.Parent).Reactive(ComponentsID<GameFrame.Runtime.View>.TID, effEntity);
    }      
}