//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoAbilityUnitTargetCampComponent
{
    
    public static void AddAbilityUnitTargetCampComponent(this GXGame.SkillManagerEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.AbilityUnitTargetCampComponent);
    }
    public static void AddAbilityUnitTargetCampComponent(this GXGame.SkillManagerEntity ecsEntity,GXGame.Camp param)
    {
        var p  =  (GXGame.AbilityUnitTargetCampComponent)ecsEntity.AddComponent(Components.AbilityUnitTargetCampComponent);
        p.AbilityUnitTargetTeam = param;
    }
                 
        
    public static GXGame.AbilityUnitTargetCampComponent GetAbilityUnitTargetCampComponent(this GXGame.SkillManagerEntity ecsEntity)
    {
        return (GXGame.AbilityUnitTargetCampComponent)ecsEntity.GetComponent(Components.AbilityUnitTargetCampComponent);
    }        
        
    public static ECSEntity SetAbilityUnitTargetCampComponent(this GXGame.SkillManagerEntity ecsEntity,GXGame.Camp param)
    {
        var p = (GXGame.AbilityUnitTargetCampComponent)ecsEntity.GetComponent(Components.AbilityUnitTargetCampComponent);
        p.AbilityUnitTargetTeam = param;
        
        ((Context)ecsEntity.Parent).Reactive(Components.AbilityUnitTargetCampComponent, ecsEntity);
        return ecsEntity;
    }     
}