//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
public static class Components {
    
    public const int Destroy= 0;
    public const int View= 1;
    public const int WorldPos= 2;
    public const int WorldRotate= 3;
    public const int LocalPos= 4;
    public const int LocalRotate= 5;
    public const int LocalScale= 6;
    public const int Direction= 7;
    public const int DirectionSpeed= 8;
    public const int MeshRendererColor= 9;
    public const int UseShareMaterial= 10;
    public const int InputDirection= 11;
    public const int MoveDirection= 12;
    public const int MoveSpeed= 13;
    public const int ViewType= 14;
    public const int CampComponent= 15;
    public const int UnitTypeComponent= 16;
    public const int SkillComponent= 17;
    public const int SkillSoundPathComponent= 18;
    public const int SkillSoundTargetComponent= 19;
    public const int SkillPlayModelPathComponent= 20;
    public const int SkillModelTargetComponent= 21;
    public const int SkillEffectComponent= 22;
    public const int SkillEffectEntityComponent= 23;
    public const int SkillIsEffectComponent= 24;
    public const int SkillEffectTargetComponent= 25;
    public const int AbilityCastPointComponent= 26;
    public const int AbilityCastRangeComponent= 27;
    public const int AbilityCooldownComponent= 28;
    public const int AbilityCurCooldownComponent= 29;
    public const int AbilityUnitTargetCampComponent= 30;
    public const int AbilityUnitTypeComponent= 31;
    public const int OnSpellStartComponent= 32;
    public const int SkillAbilityBehaviorComponent= 33;
    public const int SkillCollisionShapeComponent= 34;
    public const int SkillCollisionRadiusComponent= 35;
    public const int SkillGroupComponent= 36;
    public const int SkillIDComponent= 37;
    public const int SkillManagerStateComponent= 38;
    public const int SkillOwnerComponent= 39;
    
    public const int TotalComponents = 40;
    
    
    public static readonly System.Type[] ComponentTypes = {
        
        typeof(GameFrame.Destroy),
        typeof(GameFrame.View),
        typeof(GXGame.WorldPos),
        typeof(GXGame.WorldRotate),
        typeof(GXGame.LocalPos),
        typeof(GXGame.LocalRotate),
        typeof(GXGame.LocalScale),
        typeof(GXGame.Direction),
        typeof(GXGame.DirectionSpeed),
        typeof(GXGame.MeshRendererColor),
        typeof(GXGame.UseShareMaterial),
        typeof(GXGame.InputDirection),
        typeof(GXGame.MoveDirection),
        typeof(GXGame.MoveSpeed),
        typeof(GXGame.ViewType),
        typeof(GXGame.CampComponent),
        typeof(GXGame.UnitTypeComponent),
        typeof(GXGame.SkillComponent),
        typeof(GXGame.SkillSoundPathComponent),
        typeof(GXGame.SkillSoundTargetComponent),
        typeof(GXGame.SkillPlayModelPathComponent),
        typeof(GXGame.SkillModelTargetComponent),
        typeof(GXGame.SkillEffectComponent),
        typeof(GXGame.SkillEffectEntityComponent),
        typeof(GXGame.SkillIsEffectComponent),
        typeof(GXGame.SkillEffectTargetComponent),
        typeof(GXGame.AbilityCastPointComponent),
        typeof(GXGame.AbilityCastRangeComponent),
        typeof(GXGame.AbilityCooldownComponent),
        typeof(GXGame.AbilityCurCooldownComponent),
        typeof(GXGame.AbilityUnitTargetCampComponent),
        typeof(GXGame.AbilityUnitTypeComponent),
        typeof(GXGame.OnSpellStartComponent),
        typeof(GXGame.SkillAbilityBehaviorComponent),
        typeof(GXGame.SkillCollisionShapeComponent),
        typeof(GXGame.SkillCollisionRadiusComponent),
        typeof(GXGame.SkillGroupComponent),
        typeof(GXGame.SkillIDComponent),
        typeof(GXGame.SkillManagerStateComponent),
        typeof(GXGame.SkillOwnerComponent),
    };

    
    public static void SetComponent()
    {
       GXComponents.ComponentTypes = ComponentTypes;   
    }
}
