//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoOnSpellStartComponent
{
    
    public static void AddOnSpellStartComponent(this GXGame.SkillManagerEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.OnSpellStartComponent);
    }
    
    public static void AddOnSpellStartComponent(this GXGame.SkillManagerEntity ecsEntity,UnityEngine.KeyCode param)
    {
        var p  =  (GXGame.OnSpellStartComponent)ecsEntity.AddComponent(Components.OnSpellStartComponent);
        p.KeyCode = param;
    }
          
    public static GXGame.OnSpellStartComponent GetOnSpellStartComponent(this GXGame.SkillManagerEntity ecsEntity)
    {
        return (GXGame.OnSpellStartComponent)ecsEntity.GetComponent(Components.OnSpellStartComponent);
    }
     
    public static ECSEntity SetOnSpellStartComponent(this GXGame.SkillManagerEntity ecsEntity,UnityEngine.KeyCode param)
    {
        var p = (GXGame.OnSpellStartComponent)ecsEntity.GetComponent(Components.OnSpellStartComponent);
        p.KeyCode = param;
        
        ((Context)ecsEntity.Parent).Reactive(Components.OnSpellStartComponent, ecsEntity);
        return ecsEntity;
    }
         
}