//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoSkillEffectTargetComponent
{
    
    public static void AddSkillEffectTargetComponent(this GXGame.SkillEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.SkillEffectTargetComponent);
    }
    
    public static void AddSkillEffectTargetComponent(this GXGame.SkillEntity ecsEntity,GXGame.SkillTargetEnum[] param)
    {
        var p  =  (GXGame.SkillEffectTargetComponent)ecsEntity.AddComponent(Components.SkillEffectTargetComponent);
        p.SkillTargetEnum = param;
    }
          
    public static GXGame.SkillEffectTargetComponent GetSkillEffectTargetComponent(this GXGame.SkillEntity ecsEntity)
    {
        return (GXGame.SkillEffectTargetComponent)ecsEntity.GetComponent(Components.SkillEffectTargetComponent);
    }
     
    public static ECSEntity SetSkillEffectTargetComponent(this GXGame.SkillEntity ecsEntity,GXGame.SkillTargetEnum[] param)
    {
        var p = (GXGame.SkillEffectTargetComponent)ecsEntity.GetComponent(Components.SkillEffectTargetComponent);
        p.SkillTargetEnum = param;
        
        ((World)ecsEntity.Parent).Reactive(Components.SkillEffectTargetComponent, ecsEntity);
        return ecsEntity;
    }
         
}