//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoSkillEffectEntityComponent
{
    
    public static void AddSkillEffectEntityComponent(this GXGame.SkillEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.SkillEffectEntityComponent);
    }
    
    public static void AddSkillEffectEntityComponent(this GXGame.SkillEntity ecsEntity,GXGame.SkillEffectEntity param)
    {
        var p  =  (GXGame.SkillEffectEntityComponent)ecsEntity.AddComponent(Components.SkillEffectEntityComponent);
        p.Effect = param;
    }
          
    public static GXGame.SkillEffectEntityComponent GetSkillEffectEntityComponent(this GXGame.SkillEntity ecsEntity)
    {
        return (GXGame.SkillEffectEntityComponent)ecsEntity.GetComponent(Components.SkillEffectEntityComponent);
    }
     
    public static ECSEntity SetSkillEffectEntityComponent(this GXGame.SkillEntity ecsEntity,GXGame.SkillEffectEntity param)
    {
        var p = (GXGame.SkillEffectEntityComponent)ecsEntity.GetComponent(Components.SkillEffectEntityComponent);
        p.Effect = param;
        
        ((Context)ecsEntity.Parent).Reactive(Components.SkillEffectEntityComponent, ecsEntity);
        return ecsEntity;
    }
         
}