//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoSkillSoundPathComponent
{
    
    public static void AddSkillSoundPathComponent(this GXGame.SkillEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.SkillSoundPathComponent);
    }
    
    public static void AddSkillSoundPathComponent(this GXGame.SkillEntity ecsEntity,System.String[] param)
    {
        var p  =  (GXGame.SkillSoundPathComponent)ecsEntity.AddComponent(Components.SkillSoundPathComponent);
        p.Path = param;
    }
          
    public static GXGame.SkillSoundPathComponent GetSkillSoundPathComponent(this GXGame.SkillEntity ecsEntity)
    {
        return (GXGame.SkillSoundPathComponent)ecsEntity.GetComponent(Components.SkillSoundPathComponent);
    }
     
    public static ECSEntity SetSkillSoundPathComponent(this GXGame.SkillEntity ecsEntity,System.String[] param)
    {
        var p = (GXGame.SkillSoundPathComponent)ecsEntity.GetComponent(Components.SkillSoundPathComponent);
        p.Path = param;
        
        ((World)ecsEntity.Parent).Reactive(Components.SkillSoundPathComponent, ecsEntity,EcsChangeEventState.UpdateType);
        return ecsEntity;
    }
         
}