//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame;
using UnityEngine;
public static class AutoTargetEntity
{
    
    public static void AddTargetEntity(this ECSEntity ecsEntity)
    {
        ecsEntity.AddComponent(Components.TargetEntity);
    }
    
    public static void AddTargetEntity(this ECSEntity ecsEntity,GameFrame.ECSEntity param)
    {
        var p  =  (GXGame.TargetEntity)ecsEntity.AddComponent(Components.TargetEntity);
        p.Target = param;
    }
          
    public static GXGame.TargetEntity GetTargetEntity(this ECSEntity ecsEntity)
    {
        return (GXGame.TargetEntity)ecsEntity.GetComponent(Components.TargetEntity);
    }
     
    public static ECSEntity SetTargetEntity(this ECSEntity ecsEntity,GameFrame.ECSEntity param)
    {
        var p = (GXGame.TargetEntity)ecsEntity.GetComponent(Components.TargetEntity);
        p.Target = param;
        ((World)ecsEntity.Parent).Reactive(Components.TargetEntity, ecsEntity,EcsChangeEventState.UpdateType);
        
        return ecsEntity;
    }
         
}