//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;
namespace GamePlay.Runtime
{
    public static class AutoBindEvent
    {
        public static void AddSystem()
        {
            var  eventData =  EventData.Instance;
            
        eventData.AddSourceDic(typeof(Gameplay.Runtime.MainBagPanel),typeof(GamePlay.Runtime.IUIEvent));
        eventData.AddSourceDic(typeof(Gameplay.Runtime.MainPanel),typeof(GamePlay.Runtime.IUIEvent));
        eventData.AddSourceDic(typeof(GamePlay.Runtime.MagicWorld),typeof(GamePlay.Runtime.IWorldEvent));
        eventData.AddSourceDic(typeof(GamePlay.Runtime.GameScene),typeof(GamePlay.Runtime.IWorldEvent));
        }
    }
}
