//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------
using GameFrame.Runtime;

namespace GamePlay.Runtime
{
    public class EventSend : Singleton<EventSend>
    {
       
        public void FireUIEvent(GamePlay.Runtime.UIEventMsg msg,System.Object obj)
        {
            var allEntity = EventData.Instance.GetEntity(typeof(GamePlay.Runtime.IUIEvent));
            if (allEntity == null)
            {
                return;
            }
            foreach (var entity in allEntity)
            {
                if (entity.State == IEntity.EntityState.IsRunning)
                {
                    ((GamePlay.Runtime.IUIEvent) entity).OnBagSelectChange(msg,obj);
                }
            }
            HashSetPool<IEntity>.Release(allEntity);
        }
        
        public void FireWorldEvent(GamePlay.Runtime.WorldEventMsg msg,System.Object obj)
        {
            var allEntity = EventData.Instance.GetEntity(typeof(GamePlay.Runtime.IWorldEvent));
            if (allEntity == null)
            {
                return;
            }
            foreach (var entity in allEntity)
            {
                if (entity.State == IEntity.EntityState.IsRunning)
                {
                    ((GamePlay.Runtime.IWorldEvent) entity).WorldEvent(msg,obj);
                }
            }
            HashSetPool<IEntity>.Release(allEntity);
        }
        
    }
}
